// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"
	"time"
)

const activeBranches = `-- name: ActiveBranches :many
SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at FROM sucursal WHERE activa ORDER BY nombre
`

func (q *Queries) ActiveBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, activeBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.AuthOrgID,
			&i.Name,
			&i.Active,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeSellers = `-- name: ActiveSellers :many
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE activo ORDER BY nombre
`

func (q *Queries) ActiveSellers(ctx context.Context) ([]Seller, error) {
	rows, err := q.db.Query(ctx, activeSellers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seller{}
	for rows.Next() {
		var i Seller
		if err := rows.Scan(
			&i.ID,
			&i.AuthUserID,
			&i.Name,
			&i.BranchID,
			&i.IsSeller,
			&i.Active,
			&i.From,
			&i.To,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeSources = `-- name: ActiveSources :many

SELECT id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at FROM drive_source WHERE activa ORDER BY nombre
`

// Ingest queries: read the folders, record files and bulk-load points.
func (q *Queries) ActiveSources(ctx context.Context) ([]DriveSource, error) {
	rows, err := q.db.Query(ctx, activeSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriveSource{}
	for rows.Next() {
		var i DriveSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.Type,
			&i.BranchID,
			&i.SellerID,
			&i.Credential,
			&i.Active,
			&i.ModifiedCursor,
			&i.LastScan,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allAliases = `-- name: AllAliases :many
SELECT alias, trabajador_id, sucursal_id FROM device_alias
`

type AllAliasesRow struct {
	Alias    string
	SellerID string
	BranchID *string
}

func (q *Queries) AllAliases(ctx context.Context) ([]AllAliasesRow, error) {
	rows, err := q.db.Query(ctx, allAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllAliasesRow{}
	for rows.Next() {
		var i AllAliasesRow
		if err := rows.Scan(&i.Alias, &i.SellerID, &i.BranchID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const branchByID = `-- name: BranchByID :one
SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at FROM sucursal WHERE id = $1
`

func (q *Queries) BranchByID(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, branchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const branchByName = `-- name: BranchByName :one

SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at FROM sucursal WHERE nombre = $1 LIMIT 1
`

// Find-or-create by name, for the folder-name-is-the-seller flow.
//
// Each shared Drive folder IS a seller's GPS profile, so its name identifies them
// well enough for what the panel is for: a manager looks at their branch's GPS and
// already knows who is who. Making somebody match every folder to a person by hand
// would be asking them to type in what the folder already says.
func (q *Queries) BranchByName(ctx context.Context, name string) (Branch, error) {
	row := q.db.QueryRow(ctx, branchByName, name)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const branchConfig = `-- name: BranchConfig :one
SELECT id, sucursal_id, jornada_inicio, jornada_fin, dias_laborables, parada_radio_m, parada_minutos, paso_minimo_m, sin_mov_radio_m, sin_mov_span_min, escaso_km_netos, max_velocidad_kmh, max_accuracy_m, hueco_minutos, cobertura_gap_min, cobertura_minima, tolerancia_entrada_min, tolerancia_salida_min, visita_radio_m FROM sucursal_config WHERE sucursal_id = $1
`

func (q *Queries) BranchConfig(ctx context.Context, sucursalID string) (BranchSettings, error) {
	row := q.db.QueryRow(ctx, branchConfig, sucursalID)
	var i BranchSettings
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.WorkdayStart,
		&i.WorkdayEnd,
		&i.Workdays,
		&i.StopRadiusM,
		&i.StopMinutes,
		&i.MinStepM,
		&i.NoMoveRadiusM,
		&i.NoMoveSpanMin,
		&i.LowNetKm,
		&i.MaxSpeedKmh,
		&i.MaxAccuracyM,
		&i.GapMinutes,
		&i.CoverageGapMin,
		&i.MinCoverage,
		&i.EntryToleranceMin,
		&i.ExitToleranceMin,
		&i.VisitRadiusM,
	)
	return i, err
}

const branchHolidays = `-- name: BranchHolidays :many
SELECT fecha FROM feriado
WHERE sucursal_id IS NULL OR sucursal_id = $1
`

func (q *Queries) BranchHolidays(ctx context.Context, sucursalID *string) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, branchHolidays, sucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var fecha time.Time
		if err := rows.Scan(&fecha); err != nil {
			return nil, err
		}
		items = append(items, fecha)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeImportLog = `-- name: CloseImportLog :exec
UPDATE import_log
SET fin = now(), ficheros_vistos = $2, ficheros_nuevos = $3, ficheros_error = $4,
    puntos_insertados = $5, ok = $6, detalle = $7
WHERE id = $1
`

type CloseImportLogParams struct {
	ID             string
	FilesSeen      int32
	FilesNew       int32
	FilesFailed    int32
	InsertedPoints int32
	Ok             bool
	Detail         *string
}

func (q *Queries) CloseImportLog(ctx context.Context, arg CloseImportLogParams) error {
	_, err := q.db.Exec(ctx, closeImportLog,
		arg.ID,
		arg.FilesSeen,
		arg.FilesNew,
		arg.FilesFailed,
		arg.InsertedPoints,
		arg.Ok,
		arg.Detail,
	)
	return err
}

const createBranchByName = `-- name: CreateBranchByName :one
INSERT INTO sucursal (id, nombre) VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING id, auth_org_id, nombre, activa, timezone, created_at, updated_at
`

type CreateBranchByNameParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateBranchByName(ctx context.Context, arg CreateBranchByNameParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranchByName, arg.ID, arg.Name)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSellerByName = `-- name: CreateSellerByName :one
INSERT INTO trabajador (id, nombre, sucursal_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at
`

type CreateSellerByNameParams struct {
	ID       string
	Name     string
	BranchID string
}

func (q *Queries) CreateSellerByName(ctx context.Context, arg CreateSellerByNameParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSellerByName, arg.ID, arg.Name, arg.BranchID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO drive_source (id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial)
VALUES ($1, $2, $3, $4::tipo_fuente, $5, $6,
        COALESCE(NULLIF($7::text, ''), 'principal'))
RETURNING id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at
`

type CreateSourceParams struct {
	ID         string
	Name       string
	FolderID   string
	Type       SourceType
	BranchID   *string
	SellerID   *string
	Credential string
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (DriveSource, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.Name,
		arg.FolderID,
		arg.Type,
		arg.BranchID,
		arg.SellerID,
		arg.Credential,
	)
	var i DriveSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.Type,
		&i.BranchID,
		&i.SellerID,
		&i.Credential,
		&i.Active,
		&i.ModifiedCursor,
		&i.LastScan,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStop = `-- name: CreateStop :exec
INSERT INTO stop (
    id, track_day_id, trabajador_id, sucursal_id, inicio, fin, duracion_min,
    lat, lon, radio, cliente_ref, cliente_nombre, distancia_cliente_m, seq
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateStopParams struct {
	ID          string
	TrackDayID  string
	SellerID    string
	BranchID    string
	Start       time.Time
	End         time.Time
	DurationMin int32
	Lat         float64
	Lon         float64
	Radius      *float64
	ClientRef   *string
	ClientName  *string
	ClientDistM *float64
	Seq         int32
}

func (q *Queries) CreateStop(ctx context.Context, arg CreateStopParams) error {
	_, err := q.db.Exec(ctx, createStop,
		arg.ID,
		arg.TrackDayID,
		arg.SellerID,
		arg.BranchID,
		arg.Start,
		arg.End,
		arg.DurationMin,
		arg.Lat,
		arg.Lon,
		arg.Radius,
		arg.ClientRef,
		arg.ClientName,
		arg.ClientDistM,
		arg.Seq,
	)
	return err
}

const createTestBranch = `-- name: CreateTestBranch :one
INSERT INTO sucursal (id, nombre, auth_org_id) VALUES ($1, $2, $3) RETURNING id, auth_org_id, nombre, activa, timezone, created_at, updated_at
`

type CreateTestBranchParams struct {
	ID        string
	Name      string
	AuthOrgID *string
}

// Minimal inserts, for the integration tests only: branches and sellers are really
// created from procovar-auth, not from here.
func (q *Queries) CreateTestBranch(ctx context.Context, arg CreateTestBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createTestBranch, arg.ID, arg.Name, arg.AuthOrgID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTestSeller = `-- name: CreateTestSeller :one
INSERT INTO trabajador (id, nombre, sucursal_id, auth_user_id, desde)
VALUES ($1, $2, $3, $4, COALESCE($5::date, DATE '2020-01-01'))
RETURNING id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at
`

type CreateTestSellerParams struct {
	ID         string
	Name       string
	BranchID   string
	AuthUserID *string
	From       *time.Time
}

func (q *Queries) CreateTestSeller(ctx context.Context, arg CreateTestSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createTestSeller,
		arg.ID,
		arg.Name,
		arg.BranchID,
		arg.AuthUserID,
		arg.From,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDayStops = `-- name: DeleteDayStops :exec
DELETE FROM stop WHERE track_day_id = $1
`

func (q *Queries) DeleteDayStops(ctx context.Context, trackDayID string) error {
	_, err := q.db.Exec(ctx, deleteDayStops, trackDayID)
	return err
}

const deleteFilePoints = `-- name: DeleteFilePoints :exec
DELETE FROM track_point WHERE gpx_file_id = $1
`

func (q *Queries) DeleteFilePoints(ctx context.Context, gpxFileID string) error {
	_, err := q.db.Exec(ctx, deleteFilePoints, gpxFileID)
	return err
}

const fileByDriveID = `-- name: FileByDriveID :one
SELECT id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at FROM gpx_file WHERE drive_file_id = $1
`

// The system's "I already did this". It is checked on both keys because the same
// content can turn up under another drive_file_id (copied to another folder) and
// the same drive_file_id can change content (re-uploaded after a fix).
func (q *Queries) FileByDriveID(ctx context.Context, driveFileID string) (GpxFile, error) {
	row := q.db.QueryRow(ctx, fileByDriveID, driveFileID)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Name,
		&i.FolderPath,
		&i.SizeBytes,
		&i.DriveCreatedAt,
		&i.Status,
		&i.Error,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.DateSource,
		&i.TotalPoints,
		&i.ValidPoints,
		&i.FirstFix,
		&i.LastFix,
		&i.AliasHint,
		&i.ImportedAt,
	)
	return i, err
}

const fileBySha = `-- name: FileBySha :one
SELECT id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at FROM gpx_file WHERE sha256 = $1
`

func (q *Queries) FileBySha(ctx context.Context, sha256 string) (GpxFile, error) {
	row := q.db.QueryRow(ctx, fileBySha, sha256)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Name,
		&i.FolderPath,
		&i.SizeBytes,
		&i.DriveCreatedAt,
		&i.Status,
		&i.Error,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.DateSource,
		&i.TotalPoints,
		&i.ValidPoints,
		&i.FirstFix,
		&i.LastFix,
		&i.AliasHint,
		&i.ImportedAt,
	)
	return i, err
}

const markAbsences = `-- name: MarkAbsences :execrows
INSERT INTO track_day (id, trabajador_id, sucursal_id, fecha, estado)
SELECT
    md5(t.id || ':' || to_char($1::date, 'YYYY-MM-DD')),
    t.id,
    t.sucursal_id,
    $1::date,
    'SIN_FICHERO'
FROM trabajador t
WHERE t.activo
  AND t.es_vendedor
  AND t.desde <= $1::date
  AND (t.hasta IS NULL OR t.hasta >= $1::date)
  AND ($2::text = '' OR t.sucursal_id = $2)
ON CONFLICT (trabajador_id, fecha) DO NOTHING
`

type MarkAbsencesParams struct {
	Date     time.Time
	BranchID string
}

// Marks the working day's absences: every active seller with no row ends up as
// SIN_FICHERO. Without this, "uploaded nothing" would be the absence of a row, and
// absences cannot be listed, counted, or sorted by number of misses.
func (q *Queries) MarkAbsences(ctx context.Context, arg MarkAbsencesParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAbsences, arg.Date, arg.BranchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSourceError = `-- name: MarkSourceError :exec
UPDATE drive_source
SET ultimo_barrido = now(), ultimo_error = $2, updated_at = now()
WHERE id = $1
`

type MarkSourceErrorParams struct {
	ID        string
	LastError *string
}

func (q *Queries) MarkSourceError(ctx context.Context, arg MarkSourceErrorParams) error {
	_, err := q.db.Exec(ctx, markSourceError, arg.ID, arg.LastError)
	return err
}

const openImportLog = `-- name: OpenImportLog :one
INSERT INTO import_log (id, source_id, tipo) VALUES ($1, $2, $3) RETURNING id, source_id, tipo, inicio, fin, ficheros_vistos, ficheros_nuevos, ficheros_error, puntos_insertados, ok, detalle
`

type OpenImportLogParams struct {
	ID       string
	SourceID *string
	Type     string
}

func (q *Queries) OpenImportLog(ctx context.Context, arg OpenImportLogParams) (ImportLog, error) {
	row := q.db.QueryRow(ctx, openImportLog, arg.ID, arg.SourceID, arg.Type)
	var i ImportLog
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Type,
		&i.Start,
		&i.End,
		&i.FilesSeen,
		&i.FilesNew,
		&i.FilesFailed,
		&i.InsertedPoints,
		&i.Ok,
		&i.Detail,
	)
	return i, err
}

const saveDay = `-- name: SaveDay :one
INSERT INTO track_day (
    id, trabajador_id, sucursal_id, fecha, estado, primer_fix, ultimo_fix,
    km_netos, min_movimiento, min_parado, cobertura, huecos, puntos,
    radio_dispersion, centroide_lat, centroide_lon, lugar_texto, banderas, gpx_file_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (trabajador_id, fecha) DO UPDATE SET
    estado = EXCLUDED.estado,
    primer_fix = EXCLUDED.primer_fix,
    ultimo_fix = EXCLUDED.ultimo_fix,
    km_netos = EXCLUDED.km_netos,
    min_movimiento = EXCLUDED.min_movimiento,
    min_parado = EXCLUDED.min_parado,
    cobertura = EXCLUDED.cobertura,
    huecos = EXCLUDED.huecos,
    puntos = EXCLUDED.puntos,
    radio_dispersion = EXCLUDED.radio_dispersion,
    centroide_lat = EXCLUDED.centroide_lat,
    centroide_lon = EXCLUDED.centroide_lon,
    lugar_texto = EXCLUDED.lugar_texto,
    banderas = EXCLUDED.banderas,
    gpx_file_id = EXCLUDED.gpx_file_id,
    calculado_at = now()
RETURNING id, trabajador_id, sucursal_id, fecha, estado, primer_fix, ultimo_fix, km_netos, min_movimiento, min_parado, cobertura, huecos, puntos, radio_dispersion, centroide_lat, centroide_lon, lugar_texto, banderas, gpx_file_id, calculado_at
`

type SaveDayParams struct {
	ID          string
	SellerID    string
	BranchID    string
	Date        time.Time
	Status      DayStatus
	FirstFix    *time.Time
	LastFix     *time.Time
	NetKm       float64
	MinMovement int32
	MinStopped  int32
	Coverage    float64
	Gaps        int32
	Points      int32
	SpreadM     *float64
	CentroidLat *float64
	CentroidLon *float64
	PlaceLabel  *string
	Flags       []string
	GpxFileID   *string
}

// The day is replaced whole on every recompute: it is idempotent, so reprocessing
// a file as many times as needed duplicates nothing.
func (q *Queries) SaveDay(ctx context.Context, arg SaveDayParams) (TrackDay, error) {
	row := q.db.QueryRow(ctx, saveDay,
		arg.ID,
		arg.SellerID,
		arg.BranchID,
		arg.Date,
		arg.Status,
		arg.FirstFix,
		arg.LastFix,
		arg.NetKm,
		arg.MinMovement,
		arg.MinStopped,
		arg.Coverage,
		arg.Gaps,
		arg.Points,
		arg.SpreadM,
		arg.CentroidLat,
		arg.CentroidLon,
		arg.PlaceLabel,
		arg.Flags,
		arg.GpxFileID,
	)
	var i TrackDay
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.Status,
		&i.FirstFix,
		&i.LastFix,
		&i.NetKm,
		&i.MinMovement,
		&i.MinStopped,
		&i.Coverage,
		&i.Gaps,
		&i.Points,
		&i.SpreadM,
		&i.CentroidLat,
		&i.CentroidLon,
		&i.PlaceLabel,
		&i.Flags,
		&i.GpxFileID,
		&i.ComputedAt,
	)
	return i, err
}

const saveFile = `-- name: SaveFile :one
INSERT INTO gpx_file (
    id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes,
    drive_created_at, estado, error, trabajador_id, sucursal_id, fecha,
    origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (drive_file_id) DO UPDATE SET
    sha256 = EXCLUDED.sha256,
    nombre = EXCLUDED.nombre,
    ruta_carpeta = EXCLUDED.ruta_carpeta,
    tamano_bytes = EXCLUDED.tamano_bytes,
    estado = EXCLUDED.estado,
    error = EXCLUDED.error,
    trabajador_id = EXCLUDED.trabajador_id,
    sucursal_id = EXCLUDED.sucursal_id,
    fecha = EXCLUDED.fecha,
    origen_fecha = EXCLUDED.origen_fecha,
    puntos_total = EXCLUDED.puntos_total,
    puntos_validos = EXCLUDED.puntos_validos,
    primer_fix = EXCLUDED.primer_fix,
    ultimo_fix = EXCLUDED.ultimo_fix,
    pista_alias = EXCLUDED.pista_alias,
    importado_at = now()
RETURNING id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at
`

type SaveFileParams struct {
	ID             string
	SourceID       string
	DriveFileID    string
	Sha256         string
	Name           string
	FolderPath     *string
	SizeBytes      *int32
	DriveCreatedAt *time.Time
	Status         FileStatus
	Error          *string
	SellerID       *string
	BranchID       *string
	Date           *time.Time
	DateSource     DateSource
	TotalPoints    int32
	ValidPoints    int32
	FirstFix       *time.Time
	LastFix        *time.Time
	AliasHint      *string
}

func (q *Queries) SaveFile(ctx context.Context, arg SaveFileParams) (GpxFile, error) {
	row := q.db.QueryRow(ctx, saveFile,
		arg.ID,
		arg.SourceID,
		arg.DriveFileID,
		arg.Sha256,
		arg.Name,
		arg.FolderPath,
		arg.SizeBytes,
		arg.DriveCreatedAt,
		arg.Status,
		arg.Error,
		arg.SellerID,
		arg.BranchID,
		arg.Date,
		arg.DateSource,
		arg.TotalPoints,
		arg.ValidPoints,
		arg.FirstFix,
		arg.LastFix,
		arg.AliasHint,
	)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Name,
		&i.FolderPath,
		&i.SizeBytes,
		&i.DriveCreatedAt,
		&i.Status,
		&i.Error,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.DateSource,
		&i.TotalPoints,
		&i.ValidPoints,
		&i.FirstFix,
		&i.LastFix,
		&i.AliasHint,
		&i.ImportedAt,
	)
	return i, err
}

const sellerByID = `-- name: SellerByID :one
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE id = $1
`

func (q *Queries) SellerByID(ctx context.Context, id string) (Seller, error) {
	row := q.db.QueryRow(ctx, sellerByID, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellerByNameInBranch = `-- name: SellerByNameInBranch :one
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE nombre = $1 AND sucursal_id = $2 LIMIT 1
`

type SellerByNameInBranchParams struct {
	Name     string
	BranchID string
}

func (q *Queries) SellerByNameInBranch(ctx context.Context, arg SellerByNameInBranchParams) (Seller, error) {
	row := q.db.QueryRow(ctx, sellerByNameInBranch, arg.Name, arg.BranchID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellerPointsOnDate = `-- name: SellerPointsOnDate :many
SELECT p.ts, p.lat, p.lon, p.accuracy, p.seq
FROM track_point p
WHERE p.trabajador_id = $1
  AND p.ts IS NOT NULL
  AND (p.ts AT TIME ZONE $2::text)::date = $3::date
ORDER BY p.ts
`

type SellerPointsOnDateParams struct {
	SellerID *string
	Zone     string
	Date     time.Time
}

type SellerPointsOnDateRow struct {
	Ts       *time.Time
	Lat      float64
	Lon      float64
	Accuracy *float64
	Seq      int32
}

// Every point of a seller on a local day, whichever file it came from: the day is
// recomputed from the database and not from the file that just arrived, because
// there can be several files for the same day (a morning session and an afternoon
// one) and adding them separately would give two verdicts.
func (q *Queries) SellerPointsOnDate(ctx context.Context, arg SellerPointsOnDateParams) ([]SellerPointsOnDateRow, error) {
	rows, err := q.db.Query(ctx, sellerPointsOnDate, arg.SellerID, arg.Zone, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerPointsOnDateRow{}
	for rows.Next() {
		var i SellerPointsOnDateRow
		if err := rows.Scan(
			&i.Ts,
			&i.Lat,
			&i.Lon,
			&i.Accuracy,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceByID = `-- name: SourceByID :one
SELECT id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at FROM drive_source WHERE id = $1
`

func (q *Queries) SourceByID(ctx context.Context, id string) (DriveSource, error) {
	row := q.db.QueryRow(ctx, sourceByID, id)
	var i DriveSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.Type,
		&i.BranchID,
		&i.SellerID,
		&i.Credential,
		&i.Active,
		&i.ModifiedCursor,
		&i.LastScan,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSourceCursor = `-- name: UpdateSourceCursor :exec
UPDATE drive_source
SET cursor_modificado = $2, ultimo_barrido = now(), ultimo_error = NULL, updated_at = now()
WHERE id = $1
`

type UpdateSourceCursorParams struct {
	ID             string
	ModifiedCursor *time.Time
}

func (q *Queries) UpdateSourceCursor(ctx context.Context, arg UpdateSourceCursorParams) error {
	_, err := q.db.Exec(ctx, updateSourceCursor, arg.ID, arg.ModifiedCursor)
	return err
}
