// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"
	"time"
)

const activeBranches = `-- name: ActiveBranches :many
SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at, clave, codigo FROM sucursal WHERE activa ORDER BY nombre
`

func (q *Queries) ActiveBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, activeBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.AuthOrgID,
			&i.Name,
			&i.Active,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Clave,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeSellers = `-- name: ActiveSellers :many
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE activo ORDER BY nombre
`

func (q *Queries) ActiveSellers(ctx context.Context) ([]Seller, error) {
	rows, err := q.db.Query(ctx, activeSellers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seller{}
	for rows.Next() {
		var i Seller
		if err := rows.Scan(
			&i.ID,
			&i.AuthUserID,
			&i.Name,
			&i.BranchID,
			&i.IsSeller,
			&i.Active,
			&i.From,
			&i.To,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeSources = `-- name: ActiveSources :many

SELECT id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at FROM drive_source WHERE activa ORDER BY nombre
`

// Ingest queries: read the folders, record files and bulk-load points.
func (q *Queries) ActiveSources(ctx context.Context) ([]DriveSource, error) {
	rows, err := q.db.Query(ctx, activeSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriveSource{}
	for rows.Next() {
		var i DriveSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.Type,
			&i.BranchID,
			&i.SellerID,
			&i.Credential,
			&i.Active,
			&i.ModifiedCursor,
			&i.LastScan,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeSourcesWithBranch = `-- name: ActiveSourcesWithBranch :many
SELECT f.id, f.nombre, f.folder_id, f.tipo, f.sucursal_id, f.trabajador_id, f.credencial, f.activa, f.cursor_modificado, f.ultimo_barrido, f.ultimo_error, f.created_at, f.updated_at,
       coalesce(s.nombre, '') AS branch,
       -- De quién es la carpeta, si ya se dijo. Es lo que convierte esta lista en el
       -- sitio donde se asignan los GPS: cada carpeta compartida ES el perfil de un
       -- teléfono, así que decirlo aquí resuelve TODOS sus ficheros —los que ya
       -- entraron y los que entren— de una vez.
       coalesce(t.nombre, '') AS seller,
       coalesce(g.ficheros, 0)::bigint AS ficheros,
       coalesce(to_char(g.ultima, 'YYYY-MM-DD'), '')::text AS ultima,
       -- Días desde la última ruta, que es la pregunta de verdad: no "cuándo subió"
       -- sino "cuánto lleva callado". -1 = no ha subido nunca.
       coalesce(CURRENT_DATE - g.ultima, -1)::int AS dias_callado
FROM drive_source f
LEFT JOIN sucursal s ON s.id = f.sucursal_id
LEFT JOIN trabajador t ON t.id = f.trabajador_id
LEFT JOIN (
    SELECT source_id, count(*) AS ficheros, max(fecha) AS ultima
    FROM gpx_file
    GROUP BY source_id
) g ON g.source_id = f.id
WHERE f.activa
ORDER BY coalesce(s.nombre, 'zzz'), f.nombre
`

type ActiveSourcesWithBranchRow struct {
	ID             string
	Name           string
	FolderID       string
	Type           SourceType
	BranchID       *string
	SellerID       *string
	Credential     string
	Active         bool
	ModifiedCursor *time.Time
	LastScan       *time.Time
	LastError      *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Branch         string
	Seller         string
	Ficheros       int64
	Ultima         string
	DiasCallado    int32
}

// Igual, pero con lo que hay que ver en Administración: de qué sucursal es la
// carpeta, cuántas rutas han entrado por ella y cuántos días lleva sin entrar
// ninguna.
//
// Es la pregunta que se le hace a esa pantalla: a qué vendedor le está fallando el
// GPS y desde cuándo. Sin esas cifras, una carpeta en silencio desde hace tres
// semanas se ve exactamente igual que una que subió esta mañana.
//
// La fecha sale como texto y vacía cuando no hay ninguna, en vez de nula: una fecha
// que puede faltar obliga a decidir su tipo en cuatro sitios, y aquí lo único que se
// hace con ella es escribirla en la pantalla.
func (q *Queries) ActiveSourcesWithBranch(ctx context.Context) ([]ActiveSourcesWithBranchRow, error) {
	rows, err := q.db.Query(ctx, activeSourcesWithBranch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveSourcesWithBranchRow{}
	for rows.Next() {
		var i ActiveSourcesWithBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.Type,
			&i.BranchID,
			&i.SellerID,
			&i.Credential,
			&i.Active,
			&i.ModifiedCursor,
			&i.LastScan,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Branch,
			&i.Seller,
			&i.Ficheros,
			&i.Ultima,
			&i.DiasCallado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allAliases = `-- name: AllAliases :many
SELECT alias, trabajador_id, sucursal_id FROM device_alias
`

type AllAliasesRow struct {
	Alias    string
	SellerID string
	BranchID *string
}

func (q *Queries) AllAliases(ctx context.Context) ([]AllAliasesRow, error) {
	rows, err := q.db.Query(ctx, allAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllAliasesRow{}
	for rows.Next() {
		var i AllAliasesRow
		if err := rows.Scan(&i.Alias, &i.SellerID, &i.BranchID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const branchBreakdown = `-- name: BranchBreakdown :many
SELECT
    s.nombre AS branch,
    (SELECT count(*) FROM trabajador t WHERE t.sucursal_id = s.id) AS sellers,
    (SELECT count(*) FROM gpx_file f WHERE f.sucursal_id = s.id)   AS files
FROM sucursal s
ORDER BY s.nombre
`

type BranchBreakdownRow struct {
	Branch  string
	Sellers int64
	Files   int64
}

// Qué sucursales se crearon y cuánto tiene cada una. Es lo que dice si el reparto
// por sucursal está funcionando o si todo cayó en el mismo saco.
func (q *Queries) BranchBreakdown(ctx context.Context) ([]BranchBreakdownRow, error) {
	rows, err := q.db.Query(ctx, branchBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchBreakdownRow{}
	for rows.Next() {
		var i BranchBreakdownRow
		if err := rows.Scan(&i.Branch, &i.Sellers, &i.Files); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const branchByID = `-- name: BranchByID :one
SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at, clave, codigo FROM sucursal WHERE id = $1
`

func (q *Queries) BranchByID(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, branchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Clave,
		&i.Code,
	)
	return i, err
}

const branchByKey = `-- name: BranchByKey :one

SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at, clave, codigo FROM sucursal WHERE clave = $1 LIMIT 1
`

// Find-or-create by name, for the folder-name-is-the-seller flow.
//
// Each shared Drive folder IS a seller's GPS profile, so its name identifies them
// well enough for what the panel is for: a manager looks at their branch's GPS and
// already knows who is who. Making somebody match every folder to a person by hand
// would be asking them to type in what the folder already says.
// La sucursal se busca por su CLAVE, no por su nombre: la misma cuenta viene escrita
// de varias formas ("Camagüey Procovar", "camaguey.procovar@…", "santiagoprocovar")
// y todas tienen que caer en la misma fila.
func (q *Queries) BranchByKey(ctx context.Context, key string) (Branch, error) {
	row := q.db.QueryRow(ctx, branchByKey, key)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Clave,
		&i.Code,
	)
	return i, err
}

const branchConfig = `-- name: BranchConfig :one
SELECT id, sucursal_id, jornada_inicio, jornada_fin, dias_laborables, parada_radio_m, parada_minutos, paso_minimo_m, sin_mov_radio_m, sin_mov_span_min, escaso_km_netos, max_velocidad_kmh, max_accuracy_m, hueco_minutos, cobertura_gap_min, cobertura_minima, tolerancia_entrada_min, tolerancia_salida_min, visita_radio_m FROM sucursal_config WHERE sucursal_id = $1
`

func (q *Queries) BranchConfig(ctx context.Context, sucursalID string) (BranchSettings, error) {
	row := q.db.QueryRow(ctx, branchConfig, sucursalID)
	var i BranchSettings
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.WorkdayStart,
		&i.WorkdayEnd,
		&i.Workdays,
		&i.StopRadiusM,
		&i.StopMinutes,
		&i.MinStepM,
		&i.NoMoveRadiusM,
		&i.NoMoveSpanMin,
		&i.LowNetKm,
		&i.MaxSpeedKmh,
		&i.MaxAccuracyM,
		&i.GapMinutes,
		&i.CoverageGapMin,
		&i.MinCoverage,
		&i.EntryToleranceMin,
		&i.ExitToleranceMin,
		&i.VisitRadiusM,
	)
	return i, err
}

const branchHolidays = `-- name: BranchHolidays :many
SELECT fecha FROM feriado
WHERE sucursal_id IS NULL OR sucursal_id = $1
`

func (q *Queries) BranchHolidays(ctx context.Context, sucursalID *string) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, branchHolidays, sucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var fecha time.Time
		if err := rows.Scan(&fecha); err != nil {
			return nil, err
		}
		items = append(items, fecha)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeImportLog = `-- name: CloseImportLog :exec
UPDATE import_log
SET fin = now(), ficheros_vistos = $2, ficheros_nuevos = $3, ficheros_error = $4,
    puntos_insertados = $5, ok = $6, detalle = $7
WHERE id = $1
`

type CloseImportLogParams struct {
	ID             string
	FilesSeen      int32
	FilesNew       int32
	FilesFailed    int32
	InsertedPoints int32
	Ok             bool
	Detail         *string
}

func (q *Queries) CloseImportLog(ctx context.Context, arg CloseImportLogParams) error {
	_, err := q.db.Exec(ctx, closeImportLog,
		arg.ID,
		arg.FilesSeen,
		arg.FilesNew,
		arg.FilesFailed,
		arg.InsertedPoints,
		arg.Ok,
		arg.Detail,
	)
	return err
}

const createBranchByKey = `-- name: CreateBranchByKey :one
INSERT INTO sucursal (id, nombre, clave) VALUES ($1, $2, $3)
ON CONFLICT (clave) DO UPDATE SET nombre = CASE
    WHEN sucursal.nombre ~* 'procovar$' AND EXCLUDED.nombre !~* 'procovar$' THEN EXCLUDED.nombre
    WHEN (sucursal.nombre ~* 'procovar$') = (EXCLUDED.nombre ~* 'procovar$')
         AND length(EXCLUDED.nombre) > length(sucursal.nombre) THEN EXCLUDED.nombre
    ELSE sucursal.nombre
END
RETURNING id, auth_org_id, nombre, activa, timezone, created_at, updated_at, clave, codigo
`

type CreateBranchByKeyParams struct {
	ID   string
	Name string
	Key  string
}

// Si dos empujes llegan a la vez, el segundo choca con el índice único y se queda con
// la que creó el primero, en vez de abrir otra. Así aparecieron siete "Guantánamo".
// Si ya existe, se queda con el nombre que mejor se lee: primero el que NO arrastra
// el apellido de la empresa, y a igualdad, el más largo ("Las Tunas" gana a
// "lastunas", y "Santiago" gana a "santiagoprocovar" aunque sea más corto).
func (q *Queries) CreateBranchByKey(ctx context.Context, arg CreateBranchByKeyParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranchByKey, arg.ID, arg.Name, arg.Key)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Clave,
		&i.Code,
	)
	return i, err
}

const createSellerByName = `-- name: CreateSellerByName :one
INSERT INTO trabajador (id, nombre, sucursal_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at
`

type CreateSellerByNameParams struct {
	ID       string
	Name     string
	BranchID string
}

func (q *Queries) CreateSellerByName(ctx context.Context, arg CreateSellerByNameParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSellerByName, arg.ID, arg.Name, arg.BranchID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSellerFromAuth = `-- name: CreateSellerFromAuth :one
INSERT INTO trabajador (id, nombre, sucursal_id, auth_user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auth_user_id) DO UPDATE SET nombre = EXCLUDED.nombre, updated_at = now()
RETURNING id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at
`

type CreateSellerFromAuthParams struct {
	ID         string
	Name       string
	BranchID   string
	AuthUserID *string
}

func (q *Queries) CreateSellerFromAuth(ctx context.Context, arg CreateSellerFromAuthParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSellerFromAuth,
		arg.ID,
		arg.Name,
		arg.BranchID,
		arg.AuthUserID,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO drive_source (id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial)
VALUES ($1, $2, $3, $4::tipo_fuente, $5, $6,
        COALESCE(NULLIF($7::text, ''), 'principal'))
RETURNING id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at
`

type CreateSourceParams struct {
	ID         string
	Name       string
	FolderID   string
	Type       SourceType
	BranchID   *string
	SellerID   *string
	Credential string
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (DriveSource, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.Name,
		arg.FolderID,
		arg.Type,
		arg.BranchID,
		arg.SellerID,
		arg.Credential,
	)
	var i DriveSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.Type,
		&i.BranchID,
		&i.SellerID,
		&i.Credential,
		&i.Active,
		&i.ModifiedCursor,
		&i.LastScan,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStop = `-- name: CreateStop :exec
INSERT INTO stop (
    id, track_day_id, trabajador_id, sucursal_id, inicio, fin, duracion_min,
    lat, lon, radio, cliente_ref, cliente_nombre, distancia_cliente_m, seq
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateStopParams struct {
	ID          string
	TrackDayID  string
	SellerID    string
	BranchID    string
	Start       time.Time
	End         time.Time
	DurationMin int32
	Lat         float64
	Lon         float64
	Radius      *float64
	ClientRef   *string
	ClientName  *string
	ClientDistM *float64
	Seq         int32
}

func (q *Queries) CreateStop(ctx context.Context, arg CreateStopParams) error {
	_, err := q.db.Exec(ctx, createStop,
		arg.ID,
		arg.TrackDayID,
		arg.SellerID,
		arg.BranchID,
		arg.Start,
		arg.End,
		arg.DurationMin,
		arg.Lat,
		arg.Lon,
		arg.Radius,
		arg.ClientRef,
		arg.ClientName,
		arg.ClientDistM,
		arg.Seq,
	)
	return err
}

const createTestBranch = `-- name: CreateTestBranch :one
INSERT INTO sucursal (id, nombre, auth_org_id, clave)
VALUES ($1, $2, $3,
    regexp_replace(lower(translate($2, 'áéíóúüñÁÉÍÓÚÜÑ', 'aeiouunAEIOUUN')), '[^a-z0-9]', '', 'g'))
RETURNING id, auth_org_id, nombre, activa, timezone, created_at, updated_at, clave, codigo
`

type CreateTestBranchParams struct {
	ID        string
	Name      string
	AuthOrgID *string
}

// Minimal inserts, for the integration tests only: branches and sellers are really
// created from procovar-auth, not from here.
// La clave se calcula aquí para no tener que repetirla en cada prueba: es la misma
// normalización que hace el código (sin tildes, sin espacios, minúsculas).
func (q *Queries) CreateTestBranch(ctx context.Context, arg CreateTestBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createTestBranch, arg.ID, arg.Name, arg.AuthOrgID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Clave,
		&i.Code,
	)
	return i, err
}

const createTestSeller = `-- name: CreateTestSeller :one
INSERT INTO trabajador (id, nombre, sucursal_id, auth_user_id, desde)
VALUES ($1, $2, $3, $4, COALESCE($5::date, DATE '2020-01-01'))
RETURNING id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at
`

type CreateTestSellerParams struct {
	ID         string
	Name       string
	BranchID   string
	AuthUserID *string
	From       *time.Time
}

func (q *Queries) CreateTestSeller(ctx context.Context, arg CreateTestSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createTestSeller,
		arg.ID,
		arg.Name,
		arg.BranchID,
		arg.AuthUserID,
		arg.From,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateSource = `-- name: DeactivateSource :exec
UPDATE drive_source SET activa = FALSE, updated_at = now() WHERE id = $1
`

// Dar de baja una carpeta. No se borra la fila: de ella cuelgan los ficheros que ya
// entraron, y borrarla se los llevaría por delante. Deja de barrerse, deja de salir
// en Administración y n8n deja de pedirla, que es lo que se quiere decir con
// "quítamela de ahí".
func (q *Queries) DeactivateSource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateSource, id)
	return err
}

const deleteDayStops = `-- name: DeleteDayStops :exec
DELETE FROM stop WHERE track_day_id = $1
`

func (q *Queries) DeleteDayStops(ctx context.Context, trackDayID string) error {
	_, err := q.db.Exec(ctx, deleteDayStops, trackDayID)
	return err
}

const deleteFilePoints = `-- name: DeleteFilePoints :exec
DELETE FROM track_point WHERE gpx_file_id = $1
`

func (q *Queries) DeleteFilePoints(ctx context.Context, gpxFileID string) error {
	_, err := q.db.Exec(ctx, deleteFilePoints, gpxFileID)
	return err
}

const fileByDriveID = `-- name: FileByDriveID :one
SELECT id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at FROM gpx_file WHERE drive_file_id = $1
`

// The system's "I already did this". It is checked on both keys because the same
// content can turn up under another drive_file_id (copied to another folder) and
// the same drive_file_id can change content (re-uploaded after a fix).
func (q *Queries) FileByDriveID(ctx context.Context, driveFileID string) (GpxFile, error) {
	row := q.db.QueryRow(ctx, fileByDriveID, driveFileID)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Name,
		&i.FolderPath,
		&i.SizeBytes,
		&i.DriveCreatedAt,
		&i.Status,
		&i.Error,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.DateSource,
		&i.TotalPoints,
		&i.ValidPoints,
		&i.FirstFix,
		&i.LastFix,
		&i.AliasHint,
		&i.ImportedAt,
	)
	return i, err
}

const fileByID = `-- name: FileByID :one
SELECT id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at FROM gpx_file WHERE id = $1
`

func (q *Queries) FileByID(ctx context.Context, id string) (GpxFile, error) {
	row := q.db.QueryRow(ctx, fileByID, id)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Name,
		&i.FolderPath,
		&i.SizeBytes,
		&i.DriveCreatedAt,
		&i.Status,
		&i.Error,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.DateSource,
		&i.TotalPoints,
		&i.ValidPoints,
		&i.FirstFix,
		&i.LastFix,
		&i.AliasHint,
		&i.ImportedAt,
	)
	return i, err
}

const fileBySha = `-- name: FileBySha :one
SELECT id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at FROM gpx_file WHERE sha256 = $1
`

func (q *Queries) FileBySha(ctx context.Context, sha256 string) (GpxFile, error) {
	row := q.db.QueryRow(ctx, fileBySha, sha256)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Name,
		&i.FolderPath,
		&i.SizeBytes,
		&i.DriveCreatedAt,
		&i.Status,
		&i.Error,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.DateSource,
		&i.TotalPoints,
		&i.ValidPoints,
		&i.FirstFix,
		&i.LastFix,
		&i.AliasHint,
		&i.ImportedAt,
	)
	return i, err
}

const forgetFile = `-- name: ForgetFile :exec
DELETE FROM gpx_file WHERE id = $1
`

// Olvidar un fichero para que pueda volver a entrar.
//
// La ingesta se salta lo que ya conoce (por `drive_file_id`), que es lo que evita
// procesar mil ficheros dos veces. El precio: un fichero que entró mal se queda mal
// para siempre, aunque el lector mejore. Borrando su registro, el siguiente empuje de
// n8n lo trae otra vez y se lee con el código de hoy.
//
// Los puntos se van con él por la clave foránea (ON DELETE CASCADE). El día NO se
// borra: se recalcula solo cuando el fichero vuelva a entrar.
func (q *Queries) ForgetFile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, forgetFile, id)
	return err
}

const ingestStats = `-- name: IngestStats :one
SELECT
    (SELECT count(*) FROM gpx_file)                                   AS files,
    (SELECT count(*) FROM gpx_file WHERE estado = 'PROCESADO')        AS files_ok,
    (SELECT count(*) FROM gpx_file WHERE estado = 'SIN_ASIGNAR')      AS files_unassigned,
    (SELECT count(*) FROM gpx_file WHERE estado = 'SIN_FECHA')        AS files_no_date,
    (SELECT count(*) FROM gpx_file WHERE estado = 'ERROR')            AS files_failed,
    (SELECT count(*) FROM track_point)                                AS points,
    (SELECT count(*) FROM track_day)                                  AS days,
    (SELECT count(*) FROM trabajador)                                 AS sellers,
    (SELECT count(*) FROM sucursal)                                   AS branches,
    (SELECT max(importado_at) FROM gpx_file)                          AS last_file
`

type IngestStatsRow struct {
	Files           int64
	FilesOk         int64
	FilesUnassigned int64
	FilesNoDate     int64
	FilesFailed     int64
	Points          int64
	Days            int64
	Sellers         int64
	Branches        int64
	LastFile        interface{}
}

// Un vistazo al estado de la ingesta, para vigilarla desde fuera sin abrir la base.
func (q *Queries) IngestStats(ctx context.Context) (IngestStatsRow, error) {
	row := q.db.QueryRow(ctx, ingestStats)
	var i IngestStatsRow
	err := row.Scan(
		&i.Files,
		&i.FilesOk,
		&i.FilesUnassigned,
		&i.FilesNoDate,
		&i.FilesFailed,
		&i.Points,
		&i.Days,
		&i.Sellers,
		&i.Branches,
		&i.LastFile,
	)
	return i, err
}

const knownFiles = `-- name: KnownFiles :many
SELECT drive_file_id FROM gpx_file WHERE drive_file_id = ANY($1::text[])
`

// De esta lista, cuáles ya están dentro. Es lo que permite a la ingesta saltarse lo
// hecho sin tener que mover nada en Drive.
func (q *Queries) KnownFiles(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, knownFiles, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var drive_file_id string
		if err := rows.Scan(&drive_file_id); err != nil {
			return nil, err
		}
		items = append(items, drive_file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSellerToAuth = `-- name: LinkSellerToAuth :exec
UPDATE trabajador
SET auth_user_id = $1,
    nombre = coalesce(nullif($2::text, ''), nombre),
    updated_at = now()
WHERE id = $3
`

type LinkSellerToAuthParams struct {
	AuthUserID *string
	Name       string
	ID         string
}

// Atar un trabajador ya existente a su cuenta de Accesos.
//
// Es LO QUE HAY QUE HACER y no crear otro. El trabajador que nació del nombre de una
// carpeta («ALEXANDER») lleva colgados sus dos mil días de recorrido; si al decir
// quién es se creara una persona nueva, la historia se quedaría en el muñeco viejo y
// la persona de verdad empezaría vacía. Se ata, y de paso se le pone su nombre real.
func (q *Queries) LinkSellerToAuth(ctx context.Context, arg LinkSellerToAuthParams) error {
	_, err := q.db.Exec(ctx, linkSellerToAuth, arg.AuthUserID, arg.Name, arg.ID)
	return err
}

const markAbsences = `-- name: MarkAbsences :execrows
INSERT INTO track_day (id, trabajador_id, sucursal_id, fecha, estado)
SELECT
    md5(t.id || ':' || to_char($1::date, 'YYYY-MM-DD')),
    t.id,
    t.sucursal_id,
    $1::date,
    'SIN_FICHERO'
FROM trabajador t
WHERE t.activo
  AND t.es_vendedor
  AND t.desde <= $1::date
  AND (t.hasta IS NULL OR t.hasta >= $1::date)
  AND ($2::text = '' OR t.sucursal_id = $2)
ON CONFLICT (trabajador_id, fecha) DO NOTHING
`

type MarkAbsencesParams struct {
	Date     time.Time
	BranchID string
}

// Marks the working day's absences: every active seller with no row ends up as
// SIN_FICHERO. Without this, "uploaded nothing" would be the absence of a row, and
// absences cannot be listed, counted, or sorted by number of misses.
func (q *Queries) MarkAbsences(ctx context.Context, arg MarkAbsencesParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAbsences, arg.Date, arg.BranchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSourceError = `-- name: MarkSourceError :exec
UPDATE drive_source
SET ultimo_barrido = now(), ultimo_error = $2, updated_at = now()
WHERE id = $1
`

type MarkSourceErrorParams struct {
	ID        string
	LastError *string
}

func (q *Queries) MarkSourceError(ctx context.Context, arg MarkSourceErrorParams) error {
	_, err := q.db.Exec(ctx, markSourceError, arg.ID, arg.LastError)
	return err
}

const moveSourceDataToBranch = `-- name: MoveSourceDataToBranch :exec
WITH afectados AS (
    SELECT DISTINCT f.trabajador_id
    FROM gpx_file f
    WHERE f.source_id = $2 AND f.trabajador_id IS NOT NULL
),
mueve_ficheros AS (
    UPDATE gpx_file SET sucursal_id = $1 WHERE source_id = $2
    RETURNING 1
),
mueve_dias AS (
    UPDATE track_day SET sucursal_id = $1
    WHERE trabajador_id IN (SELECT trabajador_id FROM afectados)
    RETURNING 1
)
UPDATE trabajador SET sucursal_id = $1, updated_at = now()
WHERE id IN (SELECT trabajador_id FROM afectados)
`

type MoveSourceDataToBranchParams struct {
	BranchID string
	SourceID string
}

// Lleva a su sucursal lo que ya entró por una carpeta: sus ficheros, los vendedores
// que salieron de ella y los días de esos vendedores.
//
// Hace falta porque las carpetas se dieron de alta con una credencial de relleno y
// todo cayó en una sucursal llamada "principal". Sin esto habría que borrar y volver
// a ingerir, y los ficheros ya están apartados en Drive: no volverían a entrar.
// Los PUNTOS no se tocan a propósito. Son millones y su sucursal no la mira nadie:
// el panel filtra por track_day y por gpx_file. Actualizarlos aquí convertía una
// reasignación instantánea en minutos de espera, con n8n clavado esperando la
// respuesta.
func (q *Queries) MoveSourceDataToBranch(ctx context.Context, arg MoveSourceDataToBranchParams) error {
	_, err := q.db.Exec(ctx, moveSourceDataToBranch, arg.BranchID, arg.SourceID)
	return err
}

const openImportLog = `-- name: OpenImportLog :one
INSERT INTO import_log (id, source_id, tipo) VALUES ($1, $2, $3) RETURNING id, source_id, tipo, inicio, fin, ficheros_vistos, ficheros_nuevos, ficheros_error, puntos_insertados, ok, detalle
`

type OpenImportLogParams struct {
	ID       string
	SourceID *string
	Type     string
}

func (q *Queries) OpenImportLog(ctx context.Context, arg OpenImportLogParams) (ImportLog, error) {
	row := q.db.QueryRow(ctx, openImportLog, arg.ID, arg.SourceID, arg.Type)
	var i ImportLog
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Type,
		&i.Start,
		&i.End,
		&i.FilesSeen,
		&i.FilesNew,
		&i.FilesFailed,
		&i.InsertedPoints,
		&i.Ok,
		&i.Detail,
	)
	return i, err
}

const saveDay = `-- name: SaveDay :one
INSERT INTO track_day (
    id, trabajador_id, sucursal_id, fecha, estado, primer_fix, ultimo_fix,
    km_netos, min_movimiento, min_parado, cobertura, huecos, puntos,
    radio_dispersion, centroide_lat, centroide_lon, lugar_texto, banderas, gpx_file_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (trabajador_id, fecha) DO UPDATE SET
    estado = EXCLUDED.estado,
    primer_fix = EXCLUDED.primer_fix,
    ultimo_fix = EXCLUDED.ultimo_fix,
    km_netos = EXCLUDED.km_netos,
    min_movimiento = EXCLUDED.min_movimiento,
    min_parado = EXCLUDED.min_parado,
    cobertura = EXCLUDED.cobertura,
    huecos = EXCLUDED.huecos,
    puntos = EXCLUDED.puntos,
    radio_dispersion = EXCLUDED.radio_dispersion,
    centroide_lat = EXCLUDED.centroide_lat,
    centroide_lon = EXCLUDED.centroide_lon,
    lugar_texto = EXCLUDED.lugar_texto,
    banderas = EXCLUDED.banderas,
    gpx_file_id = EXCLUDED.gpx_file_id,
    calculado_at = now()
RETURNING id, trabajador_id, sucursal_id, fecha, estado, primer_fix, ultimo_fix, km_netos, min_movimiento, min_parado, cobertura, huecos, puntos, radio_dispersion, centroide_lat, centroide_lon, lugar_texto, banderas, gpx_file_id, calculado_at
`

type SaveDayParams struct {
	ID          string
	SellerID    string
	BranchID    string
	Date        time.Time
	Status      DayStatus
	FirstFix    *time.Time
	LastFix     *time.Time
	NetKm       float64
	MinMovement int32
	MinStopped  int32
	Coverage    float64
	Gaps        int32
	Points      int32
	SpreadM     *float64
	CentroidLat *float64
	CentroidLon *float64
	PlaceLabel  *string
	Flags       []string
	GpxFileID   *string
}

// The day is replaced whole on every recompute: it is idempotent, so reprocessing
// a file as many times as needed duplicates nothing.
func (q *Queries) SaveDay(ctx context.Context, arg SaveDayParams) (TrackDay, error) {
	row := q.db.QueryRow(ctx, saveDay,
		arg.ID,
		arg.SellerID,
		arg.BranchID,
		arg.Date,
		arg.Status,
		arg.FirstFix,
		arg.LastFix,
		arg.NetKm,
		arg.MinMovement,
		arg.MinStopped,
		arg.Coverage,
		arg.Gaps,
		arg.Points,
		arg.SpreadM,
		arg.CentroidLat,
		arg.CentroidLon,
		arg.PlaceLabel,
		arg.Flags,
		arg.GpxFileID,
	)
	var i TrackDay
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.Status,
		&i.FirstFix,
		&i.LastFix,
		&i.NetKm,
		&i.MinMovement,
		&i.MinStopped,
		&i.Coverage,
		&i.Gaps,
		&i.Points,
		&i.SpreadM,
		&i.CentroidLat,
		&i.CentroidLon,
		&i.PlaceLabel,
		&i.Flags,
		&i.GpxFileID,
		&i.ComputedAt,
	)
	return i, err
}

const saveFile = `-- name: SaveFile :one
INSERT INTO gpx_file (
    id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes,
    drive_created_at, estado, error, trabajador_id, sucursal_id, fecha,
    origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (drive_file_id) DO UPDATE SET
    sha256 = EXCLUDED.sha256,
    nombre = EXCLUDED.nombre,
    ruta_carpeta = EXCLUDED.ruta_carpeta,
    tamano_bytes = EXCLUDED.tamano_bytes,
    estado = EXCLUDED.estado,
    error = EXCLUDED.error,
    trabajador_id = EXCLUDED.trabajador_id,
    sucursal_id = EXCLUDED.sucursal_id,
    fecha = EXCLUDED.fecha,
    origen_fecha = EXCLUDED.origen_fecha,
    puntos_total = EXCLUDED.puntos_total,
    puntos_validos = EXCLUDED.puntos_validos,
    primer_fix = EXCLUDED.primer_fix,
    ultimo_fix = EXCLUDED.ultimo_fix,
    pista_alias = EXCLUDED.pista_alias,
    importado_at = now()
RETURNING id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at
`

type SaveFileParams struct {
	ID             string
	SourceID       string
	DriveFileID    string
	Sha256         string
	Name           string
	FolderPath     *string
	SizeBytes      *int32
	DriveCreatedAt *time.Time
	Status         FileStatus
	Error          *string
	SellerID       *string
	BranchID       *string
	Date           *time.Time
	DateSource     DateSource
	TotalPoints    int32
	ValidPoints    int32
	FirstFix       *time.Time
	LastFix        *time.Time
	AliasHint      *string
}

func (q *Queries) SaveFile(ctx context.Context, arg SaveFileParams) (GpxFile, error) {
	row := q.db.QueryRow(ctx, saveFile,
		arg.ID,
		arg.SourceID,
		arg.DriveFileID,
		arg.Sha256,
		arg.Name,
		arg.FolderPath,
		arg.SizeBytes,
		arg.DriveCreatedAt,
		arg.Status,
		arg.Error,
		arg.SellerID,
		arg.BranchID,
		arg.Date,
		arg.DateSource,
		arg.TotalPoints,
		arg.ValidPoints,
		arg.FirstFix,
		arg.LastFix,
		arg.AliasHint,
	)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Name,
		&i.FolderPath,
		&i.SizeBytes,
		&i.DriveCreatedAt,
		&i.Status,
		&i.Error,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.DateSource,
		&i.TotalPoints,
		&i.ValidPoints,
		&i.FirstFix,
		&i.LastFix,
		&i.AliasHint,
		&i.ImportedAt,
	)
	return i, err
}

const sellerByID = `-- name: SellerByID :one
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE id = $1
`

func (q *Queries) SellerByID(ctx context.Context, id string) (Seller, error) {
	row := q.db.QueryRow(ctx, sellerByID, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellerByNameInBranch = `-- name: SellerByNameInBranch :one
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE nombre = $1 AND sucursal_id = $2 LIMIT 1
`

type SellerByNameInBranchParams struct {
	Name     string
	BranchID string
}

func (q *Queries) SellerByNameInBranch(ctx context.Context, arg SellerByNameInBranchParams) (Seller, error) {
	row := q.db.QueryRow(ctx, sellerByNameInBranch, arg.Name, arg.BranchID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellerPointsOnDate = `-- name: SellerPointsOnDate :many
SELECT p.ts, p.lat, p.lon, p.accuracy, p.seq
FROM track_point p
WHERE p.trabajador_id = $1
  AND p.ts IS NOT NULL
  AND (p.ts AT TIME ZONE $2::text)::date = $3::date
ORDER BY p.ts
`

type SellerPointsOnDateParams struct {
	SellerID *string
	Zone     string
	Date     time.Time
}

type SellerPointsOnDateRow struct {
	Ts       *time.Time
	Lat      float64
	Lon      float64
	Accuracy *float64
	Seq      int32
}

// Every point of a seller on a local day, whichever file it came from: the day is
// recomputed from the database and not from the file that just arrived, because
// there can be several files for the same day (a morning session and an afternoon
// one) and adding them separately would give two verdicts.
func (q *Queries) SellerPointsOnDate(ctx context.Context, arg SellerPointsOnDateParams) ([]SellerPointsOnDateRow, error) {
	rows, err := q.db.Query(ctx, sellerPointsOnDate, arg.SellerID, arg.Zone, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerPointsOnDateRow{}
	for rows.Next() {
		var i SellerPointsOnDateRow
		if err := rows.Scan(
			&i.Ts,
			&i.Lat,
			&i.Lon,
			&i.Accuracy,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSourceBranch = `-- name: SetSourceBranch :exec
UPDATE drive_source SET sucursal_id = $1, credencial = $2, updated_at = now()
WHERE id = $3
`

type SetSourceBranchParams struct {
	BranchID   *string
	Credential string
	ID         string
}

func (q *Queries) SetSourceBranch(ctx context.Context, arg SetSourceBranchParams) error {
	_, err := q.db.Exec(ctx, setSourceBranch, arg.BranchID, arg.Credential, arg.ID)
	return err
}

const setSourceSeller = `-- name: SetSourceSeller :exec
UPDATE drive_source
SET trabajador_id = $1,
    tipo = 'VENDEDOR',
    sucursal_id = coalesce($2, sucursal_id),
    updated_at = now()
WHERE id = $3
`

type SetSourceSellerParams struct {
	SellerID *string
	BranchID *string
	ID       string
}

// Decir de quién es una CARPETA, que es de quién es el GPS.
//
// Cada carpeta compartida de Drive es el perfil de un teléfono, así que esto es la
// asignación de verdad: con `tipo = VENDEDOR` y un dueño, la primera regla de
// resolución acierta sin mirar nada más y TODOS los ficheros que entren por ahí caen
// solos. Teclear un alias por dispositivo era hacer a mano, uno a uno, lo que la
// carpeta ya decía.
func (q *Queries) SetSourceSeller(ctx context.Context, arg SetSourceSellerParams) error {
	_, err := q.db.Exec(ctx, setSourceSeller, arg.SellerID, arg.BranchID, arg.ID)
	return err
}

const sourceByID = `-- name: SourceByID :one
SELECT id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at FROM drive_source WHERE id = $1
`

func (q *Queries) SourceByID(ctx context.Context, id string) (DriveSource, error) {
	row := q.db.QueryRow(ctx, sourceByID, id)
	var i DriveSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderID,
		&i.Type,
		&i.BranchID,
		&i.SellerID,
		&i.Credential,
		&i.Active,
		&i.ModifiedCursor,
		&i.LastScan,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const truncatedFilesOfDay = `-- name: TruncatedFilesOfDay :one
SELECT count(*)::int AS files
FROM gpx_file
WHERE trabajador_id = $1::text
  AND fecha = $2::date
  AND estado = 'PROCESADO'
  AND error IS NOT NULL AND error <> ''
`

type TruncatedFilesOfDayParams struct {
	SellerID string
	Date     time.Time
}

// Cuántos ficheros de ese día entraron CORTADOS.
//
// Un fichero cortado se procesa igual —sus puntos son buenos— pero deja su aviso
// escrito en `error` con el estado en PROCESADO, que es la combinación que significa
// «se pudo usar, pero no está entero». El día se marca a partir de esto: sin la
// marca, medio día de recorrido se lee como el día completo.
func (q *Queries) TruncatedFilesOfDay(ctx context.Context, arg TruncatedFilesOfDayParams) (int32, error) {
	row := q.db.QueryRow(ctx, truncatedFilesOfDay, arg.SellerID, arg.Date)
	var files int32
	err := row.Scan(&files)
	return files, err
}

const unassignedFilesOfSource = `-- name: UnassignedFilesOfSource :many
SELECT id, fecha FROM gpx_file
WHERE source_id = $1 AND estado = 'SIN_ASIGNAR'
ORDER BY fecha
`

type UnassignedFilesOfSourceRow struct {
	ID   string
	Date *time.Time
}

// Los ficheros de esa carpeta que se quedaron sin dueño. Al asignar la carpeta se
// resuelven de una tacada: son los días que estaban esperando a que alguien dijera
// quién era ese teléfono.
func (q *Queries) UnassignedFilesOfSource(ctx context.Context, sourceID string) ([]UnassignedFilesOfSourceRow, error) {
	rows, err := q.db.Query(ctx, unassignedFilesOfSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnassignedFilesOfSourceRow{}
	for rows.Next() {
		var i UnassignedFilesOfSourceRow
		if err := rows.Scan(&i.ID, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceCursor = `-- name: UpdateSourceCursor :exec
UPDATE drive_source
SET cursor_modificado = $2, ultimo_barrido = now(), ultimo_error = NULL, updated_at = now()
WHERE id = $1
`

type UpdateSourceCursorParams struct {
	ID             string
	ModifiedCursor *time.Time
}

func (q *Queries) UpdateSourceCursor(ctx context.Context, arg UpdateSourceCursorParams) error {
	_, err := q.db.Exec(ctx, updateSourceCursor, arg.ID, arg.ModifiedCursor)
	return err
}
