// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type DateSource string

const (
	OrigenFechaPUNTOS  DateSource = "PUNTOS"
	OrigenFechaNOMBRE  DateSource = "NOMBRE"
	OrigenFechaDRIVE   DateSource = "DRIVE"
	OrigenFechaNINGUNO DateSource = "NINGUNO"
)

func (e *DateSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DateSource(s)
	case string:
		*e = DateSource(s)
	default:
		return fmt.Errorf("unsupported scan type for DateSource: %T", src)
	}
	return nil
}

type NullDateSource struct {
	DateSource DateSource
	Valid      bool // Valid is true if DateSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDateSource) Scan(value interface{}) error {
	if value == nil {
		ns.DateSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DateSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDateSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DateSource), nil
}

type DayStatus string

const (
	EstadoDiaOK               DayStatus = "OK"
	EstadoDiaSINFICHERO       DayStatus = "SIN_FICHERO"
	EstadoDiaSINFECHA         DayStatus = "SIN_FECHA"
	EstadoDiaSINMOVIMIENTO    DayStatus = "SIN_MOVIMIENTO"
	EstadoDiaMOVIMIENTOESCASO DayStatus = "MOVIMIENTO_ESCASO"
	EstadoDiaNOLABORABLE      DayStatus = "NO_LABORABLE"
)

func (e *DayStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DayStatus(s)
	case string:
		*e = DayStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DayStatus: %T", src)
	}
	return nil
}

type NullDayStatus struct {
	DayStatus DayStatus
	Valid     bool // Valid is true if DayStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDayStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DayStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DayStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDayStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DayStatus), nil
}

type FileStatus string

const (
	EstadoFicheroPROCESADO  FileStatus = "PROCESADO"
	EstadoFicheroSINASIGNAR FileStatus = "SIN_ASIGNAR"
	EstadoFicheroSINFECHA   FileStatus = "SIN_FECHA"
	EstadoFicheroERROR      FileStatus = "ERROR"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type NullFileStatus struct {
	FileStatus FileStatus
	Valid      bool // Valid is true if FileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatus), nil
}

type PointQuality string

const (
	CalidadPuntoOK        PointQuality = "OK"
	CalidadPuntoSALTO     PointQuality = "SALTO"
	CalidadPuntoIMPRECISO PointQuality = "IMPRECISO"
	CalidadPuntoDUPLICADO PointQuality = "DUPLICADO"
	CalidadPuntoSINHORA   PointQuality = "SIN_HORA"
)

func (e *PointQuality) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PointQuality(s)
	case string:
		*e = PointQuality(s)
	default:
		return fmt.Errorf("unsupported scan type for PointQuality: %T", src)
	}
	return nil
}

type NullPointQuality struct {
	PointQuality PointQuality
	Valid        bool // Valid is true if PointQuality is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPointQuality) Scan(value interface{}) error {
	if value == nil {
		ns.PointQuality, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PointQuality.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPointQuality) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PointQuality), nil
}

type SourceType string

const (
	TipoFuenteSUCURSAL SourceType = "SUCURSAL"
	TipoFuenteVENDEDOR SourceType = "VENDEDOR"
	TipoFuenteMIXTA    SourceType = "MIXTA"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType
	Valid      bool // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type Branch struct {
	ID        string
	AuthOrgID *string
	Name      string
	Active    bool
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Clave     string
	Code      *string
}

type BranchSettings struct {
	ID                string
	BranchID          string
	WorkdayStart      string
	WorkdayEnd        string
	Workdays          []int32
	StopRadiusM       int32
	StopMinutes       int32
	MinStepM          int32
	NoMoveRadiusM     int32
	NoMoveSpanMin     int32
	LowNetKm          float64
	MaxSpeedKmh       int32
	MaxAccuracyM      int32
	GapMinutes        int32
	CoverageGapMin    int32
	MinCoverage       float64
	EntryToleranceMin int32
	ExitToleranceMin  int32
	VisitRadiusM      int32
}

type Client struct {
	ID           string
	BranchID     string
	Ref          string
	Code         *string
	Name         string
	Address      *string
	Municipality *string
	Zone         *string
	Lat          float64
	Lon          float64
	UpdatedAt    time.Time
}

type DeviceAlias struct {
	ID            string
	Alias         string
	OriginalAlias string
	SellerID      string
	BranchID      *string
	CreatedAt     time.Time
	CreatedBy     *string
}

type DriveSource struct {
	ID             string
	Name           string
	FolderID       string
	Type           SourceType
	BranchID       *string
	SellerID       *string
	Credential     string
	Active         bool
	ModifiedCursor *time.Time
	LastScan       *time.Time
	LastError      *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GpxFile struct {
	ID             string
	SourceID       string
	DriveFileID    string
	Sha256         string
	Name           string
	FolderPath     *string
	SizeBytes      *int32
	DriveCreatedAt *time.Time
	Status         FileStatus
	Error          *string
	SellerID       *string
	BranchID       *string
	Date           *time.Time
	DateSource     DateSource
	TotalPoints    int32
	ValidPoints    int32
	FirstFix       *time.Time
	LastFix        *time.Time
	AliasHint      *string
	ImportedAt     time.Time
}

type Holiday struct {
	ID       string
	Date     time.Time
	Name     string
	BranchID *string
}

type ImportLog struct {
	ID             string
	SourceID       *string
	Type           string
	Start          time.Time
	End            *time.Time
	FilesSeen      int32
	FilesNew       int32
	FilesFailed    int32
	InsertedPoints int32
	Ok             bool
	Detail         *string
}

type Order struct {
	ID              string
	BranchID        string
	Ref             string
	Folio           *string
	Date            time.Time
	ClientID        *string
	VendorRef       *string
	VendorCode      *string
	VendorName      *string
	SellerID        *string
	Status          *string
	NeedsDelivery   bool
	UpdatedAt       time.Time
	SourceUpdatedAt *time.Time
}

type OrderSync struct {
	ID      string
	Type    string
	Start   time.Time
	End     *time.Time
	Clients int32
	Orders  int32
	Crosses int32
	Ok      bool
	Detail  *string
}

type Seller struct {
	ID         string
	AuthUserID *string
	Name       string
	BranchID   string
	IsSeller   bool
	Active     bool
	From       time.Time
	To         *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type SellerLink struct {
	ID         string
	BranchID   string
	SellerID   string
	VendorCode string
	VendorName string
	Origin     string
	CreatedAt  time.Time
}

type Stop struct {
	ID          string
	TrackDayID  string
	SellerID    string
	BranchID    string
	Start       time.Time
	End         time.Time
	DurationMin int32
	Lat         float64
	Lon         float64
	Radius      *float64
	ClientRef   *string
	ClientName  *string
	ClientDistM *float64
	Seq         int32
}

type Supervision struct {
	ID           string
	ManagerID    string
	SupervisorID string
	From         time.Time
	To           *time.Time
	CreatedAt    time.Time
}

type TrackDay struct {
	ID          string
	SellerID    string
	BranchID    string
	Date        time.Time
	Status      DayStatus
	FirstFix    *time.Time
	LastFix     *time.Time
	NetKm       float64
	MinMovement int32
	MinStopped  int32
	Coverage    float64
	Gaps        int32
	Points      int32
	SpreadM     *float64
	CentroidLat *float64
	CentroidLon *float64
	PlaceLabel  *string
	Flags       []string
	GpxFileID   *string
	ComputedAt  time.Time
}

type TrackPoint struct {
	ID        int64
	GpxFileID string
	SellerID  *string
	BranchID  *string
	Ts        *time.Time
	Lat       float64
	Lon       float64
	Ele       *float64
	Speed     *float64
	Accuracy  *float64
	Seq       int32
	Quality   PointQuality
}

type Visitum struct {
	ID         string
	TrackDayID string
	PedidoID   string
	ClientID   string
	StopID     *string
	Visited    bool
	DistanceM  *float64
	Time       *time.Time
	Minutes    *int32
	ComputedAt time.Time
}
