// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: panel.sql

package store

import (
	"context"
	"time"
)

const assignFile = `-- name: AssignFile :one
UPDATE gpx_file
SET trabajador_id = $1,
    sucursal_id = $2,
    fecha = coalesce($3::date, fecha),
    estado = CASE WHEN coalesce($3::date, fecha) IS NULL THEN 'SIN_FECHA'::estado_fichero
                  ELSE 'PROCESADO'::estado_fichero END
WHERE id = $4
RETURNING id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at
`

type AssignFileParams struct {
	SellerID *string
	BranchID *string
	Date     *time.Time
	ID       string
}

func (q *Queries) AssignFile(ctx context.Context, arg AssignFileParams) (GpxFile, error) {
	row := q.db.QueryRow(ctx, assignFile,
		arg.SellerID,
		arg.BranchID,
		arg.Date,
		arg.ID,
	)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Name,
		&i.FolderPath,
		&i.SizeBytes,
		&i.DriveCreatedAt,
		&i.Status,
		&i.Error,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.DateSource,
		&i.TotalPoints,
		&i.ValidPoints,
		&i.FirstFix,
		&i.LastFix,
		&i.AliasHint,
		&i.ImportedAt,
	)
	return i, err
}

const branchAliases = `-- name: BranchAliases :many
SELECT a.id, a.alias, a.alias_original, a.trabajador_id, a.sucursal_id, a.created_at, a.created_by, t.nombre AS seller
FROM device_alias a
JOIN trabajador t ON t.id = a.trabajador_id
WHERE $1::text = '' OR a.sucursal_id = $1
ORDER BY a.alias_original
`

type BranchAliasesRow struct {
	ID            string
	Alias         string
	OriginalAlias string
	SellerID      string
	BranchID      *string
	CreatedAt     time.Time
	CreatedBy     *string
	Seller        string
}

func (q *Queries) BranchAliases(ctx context.Context, branchID string) ([]BranchAliasesRow, error) {
	rows, err := q.db.Query(ctx, branchAliases, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchAliasesRow{}
	for rows.Next() {
		var i BranchAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.OriginalAlias,
			&i.SellerID,
			&i.BranchID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const branchByAuthOrg = `-- name: BranchByAuthOrg :one
SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at, clave, codigo FROM sucursal WHERE auth_org_id = $1
`

func (q *Queries) BranchByAuthOrg(ctx context.Context, authOrgID *string) (Branch, error) {
	row := q.db.QueryRow(ctx, branchByAuthOrg, authOrgID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Name,
		&i.Active,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Clave,
		&i.Code,
	)
	return i, err
}

const calendar = `-- name: Calendar :many

SELECT
    d.trabajador_id,
    t.nombre AS seller,
    d.sucursal_id,
    coalesce(s.nombre, '') AS branch,
    d.fecha,
    d.estado,
    d.km_netos,
    d.cobertura,
    d.primer_fix,
    d.ultimo_fix,
    d.banderas,
    d.radio_dispersion,
    d.lugar_texto
FROM track_day d
JOIN trabajador t ON t.id = d.trabajador_id
LEFT JOIN sucursal s ON s.id = d.sucursal_id
WHERE d.fecha BETWEEN $1::date AND $2::date
  AND ($3::text = '' OR d.sucursal_id = $3)
  AND (cardinality($4::text[]) = 0 OR d.trabajador_id = ANY ($4))
  AND ($5::text = '' OR d.trabajador_id <> $5)
ORDER BY t.nombre, d.fecha
`

type CalendarParams struct {
	FromDate time.Time
	ToDate   time.Time
	BranchID string
	Sellers  []string
	Exclude  string
}

type CalendarRow struct {
	SellerID   string
	Seller     string
	BranchID   string
	Branch     string
	Date       time.Time
	Status     DayStatus
	NetKm      float64
	Coverage   float64
	FirstFix   *time.Time
	LastFix    *time.Time
	Flags      []string
	SpreadM    *float64
	PlaceLabel *string
}

// Panel queries. Every one of them carries THE SAME scope block:
//
//	(@branch_id = ''  OR sucursal_id = @branch_id)
//	(cardinality(@sellers) = 0 OR trabajador_id = ANY(@sellers))
//	(@exclude = ''      OR trabajador_id <> @exclude)
//
// which is the literal translation of internal/scope.Filter. It is repeated in the
// SQL because sqlc leaves no other way, but NO query builds it on its own: the
// three parameters always come out of scope.Compute. The day someone writes a new
// query without them, review should reject it.
//
// The columns stay in Spanish because the database is not being renamed; the
// translation to English happens when sqlc generates the Go (see sqlc.yaml).
// The compliance calendar: the grid of sellers × working days.
func (q *Queries) Calendar(ctx context.Context, arg CalendarParams) ([]CalendarRow, error) {
	rows, err := q.db.Query(ctx, calendar,
		arg.FromDate,
		arg.ToDate,
		arg.BranchID,
		arg.Sellers,
		arg.Exclude,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarRow{}
	for rows.Next() {
		var i CalendarRow
		if err := rows.Scan(
			&i.SellerID,
			&i.Seller,
			&i.BranchID,
			&i.Branch,
			&i.Date,
			&i.Status,
			&i.NetKm,
			&i.Coverage,
			&i.FirstFix,
			&i.LastFix,
			&i.Flags,
			&i.SpreadM,
			&i.PlaceLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlias = `-- name: CreateAlias :one
INSERT INTO device_alias (id, alias, alias_original, trabajador_id, sucursal_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (alias) DO UPDATE SET
    trabajador_id = EXCLUDED.trabajador_id,
    sucursal_id = EXCLUDED.sucursal_id
RETURNING id, alias, alias_original, trabajador_id, sucursal_id, created_at, created_by
`

type CreateAliasParams struct {
	ID            string
	Alias         string
	OriginalAlias string
	SellerID      string
	BranchID      *string
	CreatedBy     *string
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) (DeviceAlias, error) {
	row := q.db.QueryRow(ctx, createAlias,
		arg.ID,
		arg.Alias,
		arg.OriginalAlias,
		arg.SellerID,
		arg.BranchID,
		arg.CreatedBy,
	)
	var i DeviceAlias
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.OriginalAlias,
		&i.SellerID,
		&i.BranchID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const dayPoints = `-- name: DayPoints :many
SELECT p.ts, p.lat, p.lon, p.ele, p.speed, p.quality, p.seq
FROM track_point p
JOIN track_day d ON d.trabajador_id = p.trabajador_id
                AND d.fecha = (p.ts AT TIME ZONE $1::text)::date
WHERE d.id = $2
  AND p.ts IS NOT NULL
  AND to_char(p.ts AT TIME ZONE $1::text, 'HH24:MI') BETWEEN $3::text AND $4::text
ORDER BY p.ts
`

type DayPointsParams struct {
	Zone         string
	TrackDayID   string
	WorkdayStart string
	WorkdayEnd   string
}

type DayPointsRow struct {
	Ts      *time.Time
	Lat     float64
	Lon     float64
	Ele     *float64
	Speed   *float64
	Quality PointQuality
	Seq     int32
}

// The points the viewer draws. Working hours only by default; the "full day"
// switch sends @workday_start = '00:00' and @workday_end = '23:59'.
func (q *Queries) DayPoints(ctx context.Context, arg DayPointsParams) ([]DayPointsRow, error) {
	rows, err := q.db.Query(ctx, dayPoints,
		arg.Zone,
		arg.TrackDayID,
		arg.WorkdayStart,
		arg.WorkdayEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DayPointsRow{}
	for rows.Next() {
		var i DayPointsRow
		if err := rows.Scan(
			&i.Ts,
			&i.Lat,
			&i.Lon,
			&i.Ele,
			&i.Speed,
			&i.Quality,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dayStops = `-- name: DayStops :many
SELECT id, track_day_id, trabajador_id, sucursal_id, inicio, fin, duracion_min, lat, lon, radio, cliente_ref, cliente_nombre, distancia_cliente_m, seq FROM stop WHERE track_day_id = $1 ORDER BY seq
`

func (q *Queries) DayStops(ctx context.Context, trackDayID string) ([]Stop, error) {
	rows, err := q.db.Query(ctx, dayStops, trackDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stop{}
	for rows.Next() {
		var i Stop
		if err := rows.Scan(
			&i.ID,
			&i.TrackDayID,
			&i.SellerID,
			&i.BranchID,
			&i.Start,
			&i.End,
			&i.DurationMin,
			&i.Lat,
			&i.Lon,
			&i.Radius,
			&i.ClientRef,
			&i.ClientName,
			&i.ClientDistM,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAlias = `-- name: DeleteAlias :exec
DELETE FROM device_alias WHERE id = $1
`

func (q *Queries) DeleteAlias(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAlias, id)
	return err
}

const filePoints = `-- name: FilePoints :many
SELECT p.ts, p.lat, p.lon, p.ele, p.speed, p.quality, p.seq
FROM track_point p
WHERE p.gpx_file_id = $1
ORDER BY p.seq
`

type FilePointsRow struct {
	Ts      *time.Time
	Lat     float64
	Lon     float64
	Ele     *float64
	Speed   *float64
	Quality PointQuality
	Seq     int32
}

// A file with no times does not match the previous query (it has no ts), but its
// route can still be drawn: that is what these points are for, in sequence order.
func (q *Queries) FilePoints(ctx context.Context, gpxFileID string) ([]FilePointsRow, error) {
	rows, err := q.db.Query(ctx, filePoints, gpxFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilePointsRow{}
	for rows.Next() {
		var i FilePointsRow
		if err := rows.Scan(
			&i.Ts,
			&i.Lat,
			&i.Lon,
			&i.Ele,
			&i.Speed,
			&i.Quality,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inbox = `-- name: Inbox :many
SELECT f.id, f.source_id, f.drive_file_id, f.sha256, f.nombre, f.ruta_carpeta, f.tamano_bytes, f.drive_created_at, f.estado, f.error, f.trabajador_id, f.sucursal_id, f.fecha, f.origen_fecha, f.puntos_total, f.puntos_validos, f.primer_fix, f.ultimo_fix, f.pista_alias, f.importado_at, s.nombre AS source, coalesce(t.nombre, '') AS seller
FROM gpx_file f
JOIN drive_source s ON s.id = f.source_id
LEFT JOIN trabajador t ON t.id = f.trabajador_id
WHERE f.estado IN ('SIN_ASIGNAR', 'SIN_FECHA', 'ERROR')
  AND ($1::text = '' OR f.sucursal_id IS NULL OR f.sucursal_id = $1)
ORDER BY f.importado_at DESC
LIMIT $2
`

type InboxParams struct {
	BranchID  string
	LimitRows int32
}

type InboxRow struct {
	ID             string
	SourceID       string
	DriveFileID    string
	Sha256         string
	Name           string
	FolderPath     *string
	SizeBytes      *int32
	DriveCreatedAt *time.Time
	Status         FileStatus
	Error          *string
	SellerID       *string
	BranchID       *string
	Date           *time.Time
	DateSource     DateSource
	TotalPoints    int32
	ValidPoints    int32
	FirstFix       *time.Time
	LastFix        *time.Time
	AliasHint      *string
	ImportedAt     time.Time
	Source         string
	Seller         string
}

// The inbox: what ingest could not assign or date. It is what stops a file from
// being lost in silence.
func (q *Queries) Inbox(ctx context.Context, arg InboxParams) ([]InboxRow, error) {
	rows, err := q.db.Query(ctx, inbox, arg.BranchID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxRow{}
	for rows.Next() {
		var i InboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DriveFileID,
			&i.Sha256,
			&i.Name,
			&i.FolderPath,
			&i.SizeBytes,
			&i.DriveCreatedAt,
			&i.Status,
			&i.Error,
			&i.SellerID,
			&i.BranchID,
			&i.Date,
			&i.DateSource,
			&i.TotalPoints,
			&i.ValidPoints,
			&i.FirstFix,
			&i.LastFix,
			&i.AliasHint,
			&i.ImportedAt,
			&i.Source,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incidentSummary = `-- name: IncidentSummary :many
SELECT
    d.trabajador_id,
    t.nombre AS seller,
    count(*) FILTER (WHERE d.estado = 'SIN_FICHERO')    AS days_no_file,
    count(*) FILTER (WHERE d.estado = 'SIN_FECHA')      AS days_no_date,
    count(*) FILTER (WHERE d.estado = 'SIN_MOVIMIENTO') AS days_no_movement,
    count(*) FILTER (WHERE d.estado = 'OK')             AS days_ok,
    coalesce(sum(d.km_netos), 0)::float8                AS total_km
FROM track_day d
JOIN trabajador t ON t.id = d.trabajador_id
WHERE d.fecha BETWEEN $1::date AND $2::date
  AND d.estado <> 'NO_LABORABLE'
  AND ($3::text = '' OR d.sucursal_id = $3)
  AND (cardinality($4::text[]) = 0 OR d.trabajador_id = ANY ($4))
  AND ($5::text = '' OR d.trabajador_id <> $5)
GROUP BY d.trabajador_id, t.nombre
ORDER BY count(*) FILTER (WHERE d.estado = 'SIN_FICHERO')
       + count(*) FILTER (WHERE d.estado = 'SIN_FECHA')
       + count(*) FILTER (WHERE d.estado = 'SIN_MOVIMIENTO') DESC,
         t.nombre
`

type IncidentSummaryParams struct {
	FromDate time.Time
	ToDate   time.Time
	BranchID string
	Sellers  []string
	Exclude  string
}

type IncidentSummaryRow struct {
	SellerID       string
	Seller         string
	DaysNoFile     int64
	DaysNoDate     int64
	DaysNoMovement int64
	DaysOk         int64
	TotalKm        float64
}

// Postgres does NOT accept an output alias inside an ORDER BY expression (alone
// yes, summed no), so the counts are repeated here. Writing it with the aliases
// compiles in sqlc and blows up in the database: "column ... does not exist".
func (q *Queries) IncidentSummary(ctx context.Context, arg IncidentSummaryParams) ([]IncidentSummaryRow, error) {
	rows, err := q.db.Query(ctx, incidentSummary,
		arg.FromDate,
		arg.ToDate,
		arg.BranchID,
		arg.Sellers,
		arg.Exclude,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentSummaryRow{}
	for rows.Next() {
		var i IncidentSummaryRow
		if err := rows.Scan(
			&i.SellerID,
			&i.Seller,
			&i.DaysNoFile,
			&i.DaysNoDate,
			&i.DaysNoMovement,
			&i.DaysOk,
			&i.TotalKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkBranchToAuthOrg = `-- name: LinkBranchToAuthOrg :exec
UPDATE sucursal SET auth_org_id = $1, updated_at = now()
WHERE id = $2 AND (auth_org_id IS NULL OR auth_org_id = '')
`

type LinkBranchToAuthOrgParams struct {
	AuthOrgID *string
	ID        string
}

// Atar la sucursal de aquí con la organización de Accesos.
//
// Las sucursales de aquí nacieron del nombre de la cuenta de Drive y las de Accesos
// se crearon a mano, así que son las mismas con nombres distintos y sin nada que las
// una. Se atan la primera vez que entra alguien de esa sucursal, y a partir de ahí la
// búsqueda es directa.
func (q *Queries) LinkBranchToAuthOrg(ctx context.Context, arg LinkBranchToAuthOrgParams) error {
	_, err := q.db.Exec(ctx, linkBranchToAuthOrg, arg.AuthOrgID, arg.ID)
	return err
}

const recentScans = `-- name: RecentScans :many
SELECT id, source_id, tipo, inicio, fin, ficheros_vistos, ficheros_nuevos, ficheros_error, puntos_insertados, ok, detalle FROM import_log ORDER BY inicio DESC LIMIT $1
`

func (q *Queries) RecentScans(ctx context.Context, limit int32) ([]ImportLog, error) {
	rows, err := q.db.Query(ctx, recentScans, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportLog{}
	for rows.Next() {
		var i ImportLog
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Type,
			&i.Start,
			&i.End,
			&i.FilesSeen,
			&i.FilesNew,
			&i.FilesFailed,
			&i.InsertedPoints,
			&i.Ok,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerByAuthID = `-- name: SellerByAuthID :one
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE auth_user_id = $1
`

func (q *Queries) SellerByAuthID(ctx context.Context, authUserID *string) (Seller, error) {
	row := q.db.QueryRow(ctx, sellerByAuthID, authUserID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.BranchID,
		&i.IsSeller,
		&i.Active,
		&i.From,
		&i.To,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellerDay = `-- name: SellerDay :one
SELECT d.id, d.trabajador_id, d.sucursal_id, d.fecha, d.estado, d.primer_fix, d.ultimo_fix, d.km_netos, d.min_movimiento, d.min_parado, d.cobertura, d.huecos, d.puntos, d.radio_dispersion, d.centroide_lat, d.centroide_lon, d.lugar_texto, d.banderas, d.gpx_file_id, d.calculado_at, t.nombre AS seller, coalesce(s.nombre, '') AS branch
FROM track_day d
JOIN trabajador t ON t.id = d.trabajador_id
LEFT JOIN sucursal s ON s.id = d.sucursal_id
WHERE d.trabajador_id = $1 AND d.fecha = $2::date
  AND ($3::text = '' OR d.sucursal_id = $3)
  AND (cardinality($4::text[]) = 0 OR d.trabajador_id = ANY ($4))
  AND ($5::text = '' OR d.trabajador_id <> $5)
`

type SellerDayParams struct {
	SellerID string
	Date     time.Time
	BranchID string
	Sellers  []string
	Exclude  string
}

type SellerDayRow struct {
	ID          string
	SellerID    string
	BranchID    string
	Date        time.Time
	Status      DayStatus
	FirstFix    *time.Time
	LastFix     *time.Time
	NetKm       float64
	MinMovement int32
	MinStopped  int32
	Coverage    float64
	Gaps        int32
	Points      int32
	SpreadM     *float64
	CentroidLat *float64
	CentroidLon *float64
	PlaceLabel  *string
	Flags       []string
	GpxFileID   *string
	ComputedAt  time.Time
	Seller      string
	Branch      string
}

func (q *Queries) SellerDay(ctx context.Context, arg SellerDayParams) (SellerDayRow, error) {
	row := q.db.QueryRow(ctx, sellerDay,
		arg.SellerID,
		arg.Date,
		arg.BranchID,
		arg.Sellers,
		arg.Exclude,
	)
	var i SellerDayRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.BranchID,
		&i.Date,
		&i.Status,
		&i.FirstFix,
		&i.LastFix,
		&i.NetKm,
		&i.MinMovement,
		&i.MinStopped,
		&i.Coverage,
		&i.Gaps,
		&i.Points,
		&i.SpreadM,
		&i.CentroidLat,
		&i.CentroidLon,
		&i.PlaceLabel,
		&i.Flags,
		&i.GpxFileID,
		&i.ComputedAt,
		&i.Seller,
		&i.Branch,
	)
	return i, err
}

const sellerWeek = `-- name: SellerWeek :many
SELECT d.id, d.trabajador_id, d.sucursal_id, d.fecha, d.estado, d.primer_fix, d.ultimo_fix, d.km_netos, d.min_movimiento, d.min_parado, d.cobertura, d.huecos, d.puntos, d.radio_dispersion, d.centroide_lat, d.centroide_lon, d.lugar_texto, d.banderas, d.gpx_file_id, d.calculado_at
FROM track_day d
WHERE d.trabajador_id = $1
  AND d.fecha BETWEEN $2::date AND $3::date
  AND ($4::text = '' OR d.sucursal_id = $4)
  AND (cardinality($5::text[]) = 0 OR d.trabajador_id = ANY ($5))
  AND ($6::text = '' OR d.trabajador_id <> $6)
ORDER BY d.fecha
`

type SellerWeekParams struct {
	SellerID string
	FromDate time.Time
	ToDate   time.Time
	BranchID string
	Sellers  []string
	Exclude  string
}

func (q *Queries) SellerWeek(ctx context.Context, arg SellerWeekParams) ([]TrackDay, error) {
	rows, err := q.db.Query(ctx, sellerWeek,
		arg.SellerID,
		arg.FromDate,
		arg.ToDate,
		arg.BranchID,
		arg.Sellers,
		arg.Exclude,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackDay{}
	for rows.Next() {
		var i TrackDay
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.BranchID,
			&i.Date,
			&i.Status,
			&i.FirstFix,
			&i.LastFix,
			&i.NetKm,
			&i.MinMovement,
			&i.MinStopped,
			&i.Coverage,
			&i.Gaps,
			&i.Points,
			&i.SpreadM,
			&i.CentroidLat,
			&i.CentroidLon,
			&i.PlaceLabel,
			&i.Flags,
			&i.GpxFileID,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellersInScope = `-- name: SellersInScope :many
SELECT t.id, t.auth_user_id, t.nombre, t.sucursal_id, t.es_vendedor, t.activo, t.desde, t.hasta, t.created_at, t.updated_at
FROM trabajador t
WHERE t.activo AND t.es_vendedor
  AND ($1::text = '' OR t.sucursal_id = $1)
  AND (cardinality($2::text[]) = 0 OR t.id = ANY ($2))
  AND ($3::text = '' OR t.id <> $3)
ORDER BY t.nombre
`

type SellersInScopeParams struct {
	BranchID string
	Sellers  []string
	Exclude  string
}

func (q *Queries) SellersInScope(ctx context.Context, arg SellersInScopeParams) ([]Seller, error) {
	rows, err := q.db.Query(ctx, sellersInScope, arg.BranchID, arg.Sellers, arg.Exclude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seller{}
	for rows.Next() {
		var i Seller
		if err := rows.Scan(
			&i.ID,
			&i.AuthUserID,
			&i.Name,
			&i.BranchID,
			&i.IsSeller,
			&i.Active,
			&i.From,
			&i.To,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stuckDays = `-- name: StuckDays :many


SELECT f.trabajador_id::text AS seller_id, f.fecha::date AS fecha, f.estado, count(*)::int AS files
FROM gpx_file f
WHERE f.estado <> 'PROCESADO'
  AND f.trabajador_id IS NOT NULL
  AND f.fecha BETWEEN $1::date AND $2::date
  AND ($3::text = '' OR f.sucursal_id = $3)
  AND (cardinality($4::text[]) = 0 OR f.trabajador_id = ANY ($4))
  AND ($5::text = '' OR f.trabajador_id <> $5)
GROUP BY f.trabajador_id, f.fecha, f.estado
`

type StuckDaysParams struct {
	FromDate time.Time
	ToDate   time.Time
	BranchID string
	Sellers  []string
	Exclude  string
}

type StuckDaysRow struct {
	SellerID string
	Date     time.Time
	Status   FileStatus
	Files    int32
}

// ---------------------------------------------------------------------------
// Por qué no subió
// ---------------------------------------------------------------------------
//
// Un día en SIN_FICHERO decía "no hay ruta" y se quedaba callado sobre lo único que
// hay que hacer con él: si el vendedor no subió nada, si subió y el fichero se
// atascó, o si lleva un mes sin subir y lo que falla es el GPS. Eso vivía en la
// pantalla de Administración, que es donde nadie iba a mirarlo.
// Lo primero de las dos —cuándo subió cada vendedor por última vez— se escribe a
// mano en upload_state.go: sqlc no acierta a inferir qué es nulo ahí y devolvía
// `interface{}` en la mitad de las columnas.
// Los ficheros que SÍ llegaron para un día y no se pudieron usar. Es la diferencia
// entre "no subió" y "subió y el sistema no supo qué hacer con ello", que son dos
// conversaciones muy distintas con el vendedor.
func (q *Queries) StuckDays(ctx context.Context, arg StuckDaysParams) ([]StuckDaysRow, error) {
	rows, err := q.db.Query(ctx, stuckDays,
		arg.FromDate,
		arg.ToDate,
		arg.BranchID,
		arg.Sellers,
		arg.Exclude,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StuckDaysRow{}
	for rows.Next() {
		var i StuckDaysRow
		if err := rows.Scan(
			&i.SellerID,
			&i.Date,
			&i.Status,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supervisorTerms = `-- name: SupervisorTerms :many
SELECT gestor_id, supervisor_id, desde, hasta
FROM supervision
WHERE supervisor_id = $1
`

type SupervisorTermsRow struct {
	ManagerID    string
	SupervisorID string
	From         time.Time
	To           *time.Time
}

func (q *Queries) SupervisorTerms(ctx context.Context, supervisorID string) ([]SupervisorTermsRow, error) {
	rows, err := q.db.Query(ctx, supervisorTerms, supervisorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupervisorTermsRow{}
	for rows.Next() {
		var i SupervisorTermsRow
		if err := rows.Scan(
			&i.ManagerID,
			&i.SupervisorID,
			&i.From,
			&i.To,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncatedDays = `-- name: TruncatedDays :many
SELECT
    f.trabajador_id::text AS seller_id,
    coalesce(t.nombre, '') AS seller,
    f.fecha::date          AS fecha,
    f.nombre               AS file,
    coalesce(f.error, '')  AS detail,
    f.puntos_total         AS points
FROM gpx_file f
LEFT JOIN trabajador t ON t.id = f.trabajador_id
WHERE f.estado = 'PROCESADO'
  AND f.error IS NOT NULL AND f.error <> ''
  AND f.trabajador_id IS NOT NULL
  AND f.fecha IS NOT NULL
  AND ($1::text = '' OR f.sucursal_id = $1)
ORDER BY f.fecha DESC
LIMIT $2
`

type TruncatedDaysParams struct {
	BranchID  string
	LimitRows int32
}

type TruncatedDaysRow struct {
	SellerID string
	Seller   string
	Date     time.Time
	File     string
	Detail   string
	Points   int32
}

// Los días que entraron A MEDIAS: su fichero llegó cortado y lo que hay es el trozo
// que se pudo leer, no la jornada.
//
// Va en su propia consulta y no como una bandera más del calendario porque lo que se
// necesita aquí es la LISTA —quién, qué día, y qué dijo el error—, para poder ir a
// pedir que vuelvan a subir esos días concretos.
func (q *Queries) TruncatedDays(ctx context.Context, arg TruncatedDaysParams) ([]TruncatedDaysRow, error) {
	rows, err := q.db.Query(ctx, truncatedDays, arg.BranchID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TruncatedDaysRow{}
	for rows.Next() {
		var i TruncatedDaysRow
		if err := rows.Scan(
			&i.SellerID,
			&i.Seller,
			&i.Date,
			&i.File,
			&i.Detail,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
