// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pedidos.sql

package store

import (
	"context"
	"time"
)

const branchClients = `-- name: BranchClients :many
SELECT c.id, c.codigo, c.nombre, c.direccion, c.municipio, c.lat, c.lon
FROM pedido_cliente c
WHERE c.sucursal_id = $1
ORDER BY c.nombre
`

type BranchClientsRow struct {
	ID           string
	Code         *string
	Name         string
	Address      *string
	Municipality *string
	Lat          float64
	Lon          float64
}

// Toda la cartera del vendedor en la sucursal, visitada o no. Es la otra capa del
// mapa: dónde están TODOS sus clientes, no solo los que tenían pedido ese día.
func (q *Queries) BranchClients(ctx context.Context, sucursalID string) ([]BranchClientsRow, error) {
	rows, err := q.db.Query(ctx, branchClients, sucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchClientsRow{}
	for rows.Next() {
		var i BranchClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Address,
			&i.Municipality,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearDayStopClients = `-- name: ClearDayStopClients :exec
UPDATE stop SET cliente_ref = NULL, cliente_nombre = NULL, distancia_cliente_m = NULL
WHERE track_day_id = $1
`

// La parada deja de ser un punto anónimo y pasa a llamarse como el cliente al que
// se le atribuye. Se limpia antes de cada cruce: si un pedido se anula, su parada
// no puede seguir llevando su nombre.
func (q *Queries) ClearDayStopClients(ctx context.Context, trackDayID string) error {
	_, err := q.db.Exec(ctx, clearDayStopClients, trackDayID)
	return err
}

const clientPins = `-- name: ClientPins :many
SELECT ref, nombre, lat, lon FROM pedido_cliente WHERE sucursal_id = $1
`

type ClientPinsRow struct {
	Ref  string
	Name string
	Lat  float64
	Lon  float64
}

// Los pines que YA están guardados, para no volver a escribir los que no se han
// movido. Con ocho mil clientes por sucursal, la pasada horaria reescribía ocho mil
// filas idénticas para acabar dejándolo todo como estaba.
func (q *Queries) ClientPins(ctx context.Context, sucursalID string) ([]ClientPinsRow, error) {
	rows, err := q.db.Query(ctx, clientPins, sucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientPinsRow{}
	for rows.Next() {
		var i ClientPinsRow
		if err := rows.Scan(
			&i.Ref,
			&i.Name,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeOrderSync = `-- name: CloseOrderSync :exec
UPDATE pedido_sync
SET fin = now(), clientes = $2, pedidos = $3, cruces = $4, ok = $5, detalle = $6
WHERE id = $1
`

type CloseOrderSyncParams struct {
	ID      string
	Clients int32
	Orders  int32
	Crosses int32
	Ok      bool
	Detail  *string
}

func (q *Queries) CloseOrderSync(ctx context.Context, arg CloseOrderSyncParams) error {
	_, err := q.db.Exec(ctx, closeOrderSync,
		arg.ID,
		arg.Clients,
		arg.Orders,
		arg.Crosses,
		arg.Ok,
		arg.Detail,
	)
	return err
}

const createVisit = `-- name: CreateVisit :exec
INSERT INTO visita (
    id, track_day_id, pedido_id, cliente_id, stop_id, visitado, distancia_m, hora, minutos, calculado_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (track_day_id, pedido_id) DO UPDATE SET
    cliente_id = EXCLUDED.cliente_id,
    stop_id = EXCLUDED.stop_id,
    visitado = EXCLUDED.visitado,
    distancia_m = EXCLUDED.distancia_m,
    hora = EXCLUDED.hora,
    minutos = EXCLUDED.minutos,
    calculado_at = now()
`

type CreateVisitParams struct {
	ID         string
	TrackDayID string
	PedidoID   string
	ClientID   string
	StopID     *string
	Visited    bool
	DistanceM  *float64
	Time       *time.Time
	Minutes    *int32
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) error {
	_, err := q.db.Exec(ctx, createVisit,
		arg.ID,
		arg.TrackDayID,
		arg.PedidoID,
		arg.ClientID,
		arg.StopID,
		arg.Visited,
		arg.DistanceM,
		arg.Time,
		arg.Minutes,
	)
	return err
}

const dayVisits = `-- name: DayVisits :many
SELECT
    v.id,
    v.visitado,
    v.distancia_m,
    v.hora,
    v.minutos,
    v.stop_id,
    p.folio,
    p.estado    AS order_status,
    c.id        AS client_id,
    c.codigo    AS client_code,
    c.nombre    AS client_name,
    c.direccion AS client_address,
    c.municipio AS client_municipality,
    c.lat,
    c.lon
FROM visita v
JOIN pedido p ON p.id = v.pedido_id
JOIN pedido_cliente c ON c.id = v.cliente_id
WHERE v.track_day_id = $1
ORDER BY v.visitado DESC, v.hora NULLS LAST, c.nombre
`

type DayVisitsRow struct {
	ID                 string
	Visited            bool
	DistanceM          *float64
	Time               *time.Time
	Minutes            *int32
	StopID             *string
	Folio              *string
	OrderStatus        *string
	ClientID           string
	ClientCode         *string
	ClientName         string
	ClientAddress      *string
	ClientMunicipality *string
	Lat                float64
	Lon                float64
}

// Los clientes del día con su veredicto, para dibujarlos como una capa del mapa.
func (q *Queries) DayVisits(ctx context.Context, trackDayID string) ([]DayVisitsRow, error) {
	rows, err := q.db.Query(ctx, dayVisits, trackDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DayVisitsRow{}
	for rows.Next() {
		var i DayVisitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Visited,
			&i.DistanceM,
			&i.Time,
			&i.Minutes,
			&i.StopID,
			&i.Folio,
			&i.OrderStatus,
			&i.ClientID,
			&i.ClientCode,
			&i.ClientName,
			&i.ClientAddress,
			&i.ClientMunicipality,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const daysToCross = `-- name: DaysToCross :many
SELECT d.id, d.trabajador_id, d.sucursal_id, d.fecha
FROM track_day d
WHERE d.fecha BETWEEN $1::date AND $2::date
  AND EXISTS (
      SELECT 1 FROM pedido p
      WHERE p.trabajador_id = d.trabajador_id AND p.fecha = d.fecha
  )
ORDER BY d.fecha, d.trabajador_id
`

type DaysToCrossParams struct {
	FromDate time.Time
	ToDate   time.Time
}

type DaysToCrossRow struct {
	ID       string
	SellerID string
	BranchID string
	Date     time.Time
}

// Los días que hay que volver a cruzar: los que tienen pedidos en el rango. Un día
// sin pedidos no se toca — no hay nada contra qué contrastar el recorrido.
func (q *Queries) DaysToCross(ctx context.Context, arg DaysToCrossParams) ([]DaysToCrossRow, error) {
	rows, err := q.db.Query(ctx, daysToCross, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaysToCrossRow{}
	for rows.Next() {
		var i DaysToCrossRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.BranchID,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDayVisits = `-- name: DeleteDayVisits :exec
DELETE FROM visita WHERE track_day_id = $1
`

func (q *Queries) DeleteDayVisits(ctx context.Context, trackDayID string) error {
	_, err := q.db.Exec(ctx, deleteDayVisits, trackDayID)
	return err
}

const deleteOrdersOfDayNotIn = `-- name: DeleteOrdersOfDayNotIn :execrows
DELETE FROM pedido
WHERE sucursal_id = $1
  AND fecha BETWEEN $2::date AND $3::date
  AND NOT (ref = ANY ($4::text[]))
`

type DeleteOrdersOfDayNotInParams struct {
	BranchID string
	FromDate time.Time
	ToDate   time.Time
	Refs     []string
}

// Los pedidos viejos que ya no vienen en la ventana sincronizada NO se borran: el
// calendario mira semanas pasadas y borrarlos dejaría esas semanas en blanco. Solo
// se limpia lo que quedó huérfano de cliente.
func (q *Queries) DeleteOrdersOfDayNotIn(ctx context.Context, arg DeleteOrdersOfDayNotInParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrdersOfDayNotIn,
		arg.BranchID,
		arg.FromDate,
		arg.ToDate,
		arg.Refs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureDaysForOrders = `-- name: EnsureDaysForOrders :execrows

INSERT INTO track_day (id, trabajador_id, sucursal_id, fecha, estado)
SELECT DISTINCT
    md5(p.trabajador_id || ':' || to_char(p.fecha, 'YYYY-MM-DD')),
    p.trabajador_id,
    p.sucursal_id,
    p.fecha,
    -- El literal se marca como enum a mano: con el DISTINCT de arriba, Postgres le
    -- resuelve el tipo ANTES de mirar la columna y lo manda como ` + "`" + `text` + "`" + `, que la
    -- tabla rechaza. sqlc lo daba por bueno; solo se ve al ejecutarlo.
    'SIN_FICHERO'::estado_dia
FROM pedido p
WHERE p.trabajador_id IS NOT NULL
  AND p.fecha BETWEEN $1::date AND $2::date
ON CONFLICT (trabajador_id, fecha) DO NOTHING
`

type EnsureDaysForOrdersParams struct {
	FromDate time.Time
	ToDate   time.Time
}

// ---------------------------------------------------------------------------
// El cruce
// ---------------------------------------------------------------------------
// El día tiene que EXISTIR para poder colgarle las visitas, y hoy a media mañana
// todavía no existe: la fila la crea el fichero cuando el vendedor termina la
// jornada, o el repaso nocturno al día siguiente. Sin esto, «hoy tiene 8 pedidos»
// no se podría enseñar hasta mañana, que es justo cuando ya no sirve.
//
// Solo para (vendedor, día) que TIENEN pedido: eso ya implica que era día de
// trabajo. Crear la fila para todos los vendedores y todos los días del rango
// pintaría de rojo los sábados.
func (q *Queries) EnsureDaysForOrders(ctx context.Context, arg EnsureDaysForOrdersParams) (int64, error) {
	result, err := q.db.Exec(ctx, ensureDaysForOrders, arg.FromDate, arg.ToDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lastOrderCursor = `-- name: LastOrderCursor :one
SELECT coalesce(max(origen_actualizado_at), 'epoch'::timestamptz)::timestamptz AS cursor
FROM pedido
`

// Por dónde se quedó la última sincronización, sacado del propio espejo.
//
// El cursor NO se guarda aparte a propósito: un cursor en su tabla se desincroniza
// del dato el día que algo se borre a mano o falle a medias, y entonces deja de
// traerse lo que falta sin que nadie se entere. Preguntándoselo a las filas que hay,
// el cursor no puede mentir.
// Con el espejo vacío no hay cursor y sale `epoch`, que es lo que se quiere en la
// primera pasada: traerlo todo. (`coalesce` y no un nulo porque una fecha nula leída
// como no nula revienta al escanear la fila, y sqlc no acierta a inferirlo aquí.)
func (q *Queries) LastOrderCursor(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastOrderCursor)
	var cursor time.Time
	err := row.Scan(&cursor)
	return cursor, err
}

const linkOrdersToSellers = `-- name: LinkOrdersToSellers :execrows
UPDATE pedido p
SET trabajador_id = v.trabajador_id
FROM vendedor_pedido v
WHERE v.sucursal_id = p.sucursal_id
  AND v.vendedor_codigo = p.vendedor_codigo
  AND p.trabajador_id IS DISTINCT FROM v.trabajador_id
`

func (q *Queries) LinkOrdersToSellers(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, linkOrdersToSellers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const openOrderSync = `-- name: OpenOrderSync :one

INSERT INTO pedido_sync (id, tipo) VALUES ($1, $2) RETURNING id, tipo, inicio, fin, clientes, pedidos, cruces, ok, detalle
`

type OpenOrderSyncParams struct {
	ID   string
	Type string
}

// ---------------------------------------------------------------------------
// Bitácora
// ---------------------------------------------------------------------------
func (q *Queries) OpenOrderSync(ctx context.Context, arg OpenOrderSyncParams) (OrderSync, error) {
	row := q.db.QueryRow(ctx, openOrderSync, arg.ID, arg.Type)
	var i OrderSync
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Start,
		&i.End,
		&i.Clients,
		&i.Orders,
		&i.Crosses,
		&i.Ok,
		&i.Detail,
	)
	return i, err
}

const ordersForDay = `-- name: OrdersForDay :many
SELECT
    p.id                   AS order_id,
    p.folio,
    p.estado               AS order_status,
    c.id                   AS client_id,
    c.nombre               AS client_name,
    c.lat,
    c.lon
FROM pedido p
JOIN pedido_cliente c ON c.id = p.cliente_id
WHERE p.trabajador_id = $1::text AND p.fecha = $2::date
ORDER BY c.nombre
`

type OrdersForDayParams struct {
	SellerID string
	Date     time.Time
}

type OrdersForDayRow struct {
	OrderID     string
	Folio       *string
	OrderStatus *string
	ClientID    string
	ClientName  string
	Lat         float64
	Lon         float64
}

func (q *Queries) OrdersForDay(ctx context.Context, arg OrdersForDayParams) ([]OrdersForDayRow, error) {
	rows, err := q.db.Query(ctx, ordersForDay, arg.SellerID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersForDayRow{}
	for rows.Next() {
		var i OrdersForDayRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Folio,
			&i.OrderStatus,
			&i.ClientID,
			&i.ClientName,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentOrderSyncs = `-- name: RecentOrderSyncs :many
SELECT id, tipo, inicio, fin, clientes, pedidos, cruces, ok, detalle FROM pedido_sync ORDER BY inicio DESC LIMIT $1
`

func (q *Queries) RecentOrderSyncs(ctx context.Context, limit int32) ([]OrderSync, error) {
	rows, err := q.db.Query(ctx, recentOrderSyncs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderSync{}
	for rows.Next() {
		var i OrderSync
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Start,
			&i.End,
			&i.Clients,
			&i.Orders,
			&i.Crosses,
			&i.Ok,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerLinks = `-- name: SellerLinks :many
SELECT v.id, v.sucursal_id, v.trabajador_id, v.vendedor_codigo, v.vendedor_nombre, v.origen, v.created_at, t.nombre AS seller
FROM vendedor_pedido v
JOIN trabajador t ON t.id = v.trabajador_id
WHERE ($1::text = '' OR v.sucursal_id = $1)
ORDER BY v.vendedor_nombre
`

type SellerLinksRow struct {
	ID         string
	BranchID   string
	SellerID   string
	VendorCode string
	VendorName string
	Origin     string
	CreatedAt  time.Time
	Seller     string
}

func (q *Queries) SellerLinks(ctx context.Context, branchID string) ([]SellerLinksRow, error) {
	rows, err := q.db.Query(ctx, sellerLinks, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerLinksRow{}
	for rows.Next() {
		var i SellerLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.SellerID,
			&i.VendorCode,
			&i.VendorName,
			&i.Origin,
			&i.CreatedAt,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellersForMatch = `-- name: SellersForMatch :many

SELECT t.id, t.nombre, t.sucursal_id
FROM trabajador t
WHERE t.activo AND t.es_vendedor
`

type SellersForMatchRow struct {
	ID       string
	Name     string
	BranchID string
}

// ---------------------------------------------------------------------------
// Quién es quién: vendedor de PEDIDO ↔ trabajador de Rutas
// ---------------------------------------------------------------------------
func (q *Queries) SellersForMatch(ctx context.Context) ([]SellersForMatchRow, error) {
	rows, err := q.db.Query(ctx, sellersForMatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellersForMatchRow{}
	for rows.Next() {
		var i SellersForMatchRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BranchID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBranchCode = `-- name: SetBranchCode :exec
UPDATE sucursal SET codigo = $1, updated_at = now()
WHERE id = $2 AND (codigo IS NULL OR codigo <> $1)
`

type SetBranchCodeParams struct {
	Code *string
	ID   string
}

func (q *Queries) SetBranchCode(ctx context.Context, arg SetBranchCodeParams) error {
	_, err := q.db.Exec(ctx, setBranchCode, arg.Code, arg.ID)
	return err
}

const setStopClient = `-- name: SetStopClient :exec
UPDATE stop SET cliente_ref = $2, cliente_nombre = $3, distancia_cliente_m = $4
WHERE id = $1
`

type SetStopClientParams struct {
	ID          string
	ClientRef   *string
	ClientName  *string
	ClientDistM *float64
}

func (q *Queries) SetStopClient(ctx context.Context, arg SetStopClientParams) error {
	_, err := q.db.Exec(ctx, setStopClient,
		arg.ID,
		arg.ClientRef,
		arg.ClientName,
		arg.ClientDistM,
	)
	return err
}

const stopsForCross = `-- name: StopsForCross :many
SELECT id, inicio, fin, duracion_min, lat, lon
FROM stop
WHERE track_day_id = $1
ORDER BY seq
`

type StopsForCrossRow struct {
	ID          string
	Start       time.Time
	End         time.Time
	DurationMin int32
	Lat         float64
	Lon         float64
}

func (q *Queries) StopsForCross(ctx context.Context, trackDayID string) ([]StopsForCrossRow, error) {
	rows, err := q.db.Query(ctx, stopsForCross, trackDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StopsForCrossRow{}
	for rows.Next() {
		var i StopsForCrossRow
		if err := rows.Scan(
			&i.ID,
			&i.Start,
			&i.End,
			&i.DurationMin,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkedVendors = `-- name: UnlinkedVendors :many
SELECT
    p.sucursal_id,
    coalesce(s.nombre, '')      AS branch,
    p.vendedor_codigo,
    max(p.vendedor_nombre)::text AS vendor_label,
    count(*)::int               AS orders,
    max(p.fecha)::date          AS last_order
FROM pedido p
LEFT JOIN sucursal s ON s.id = p.sucursal_id
WHERE p.trabajador_id IS NULL
  AND ($1::text = '' OR p.sucursal_id = $1)
GROUP BY p.sucursal_id, s.nombre, p.vendedor_codigo
ORDER BY count(*) DESC, max(p.vendedor_nombre)
`

type UnlinkedVendorsRow struct {
	BranchID    string
	Branch      string
	VendorCode  *string
	VendorLabel string
	Orders      int32
	LastOrder   time.Time
}

// Los vendedores de PEDIDO que no se pudieron emparejar con nadie de aquí. Es
// información, no un error: mientras estén así, sus pedidos no se cruzan con
// ninguna ruta y el panel tiene que decirlo en vez de enseñar un cero.
func (q *Queries) UnlinkedVendors(ctx context.Context, branchID string) ([]UnlinkedVendorsRow, error) {
	rows, err := q.db.Query(ctx, unlinkedVendors, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnlinkedVendorsRow{}
	for rows.Next() {
		var i UnlinkedVendorsRow
		if err := rows.Scan(
			&i.BranchID,
			&i.Branch,
			&i.VendorCode,
			&i.VendorLabel,
			&i.Orders,
			&i.LastOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClient = `-- name: UpsertClient :exec


INSERT INTO pedido_cliente (
    id, sucursal_id, ref, codigo, nombre, direccion, municipio, zona, lat, lon, actualizado_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (sucursal_id, ref) DO UPDATE SET
    codigo = EXCLUDED.codigo,
    nombre = EXCLUDED.nombre,
    direccion = EXCLUDED.direccion,
    municipio = EXCLUDED.municipio,
    zona = EXCLUDED.zona,
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    actualizado_at = now()
`

type UpsertClientParams struct {
	ID           string
	BranchID     string
	Ref          string
	Code         *string
	Name         string
	Address      *string
	Municipality *string
	Zone         *string
	Lat          float64
	Lon          float64
}

// El espejo de PEDIDO y el cruce de sus pedidos con el recorrido.
//
// Nada de aquí escribe en PEDIDO: es su dato y allí se queda. Lo que se guarda es
// una copia reconciliable —clave (sucursal, ref)— que se puede tirar y volver a
// traer sincronizando.
//
// Las columnas siguen en español porque la base no se renombra; los ALIAS de estas
// consultas se escriben en inglés directamente, que es como sale el Go.
// ---------------------------------------------------------------------------
// Espejo
// ---------------------------------------------------------------------------
func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.Exec(ctx, upsertClient,
		arg.ID,
		arg.BranchID,
		arg.Ref,
		arg.Code,
		arg.Name,
		arg.Address,
		arg.Municipality,
		arg.Zone,
		arg.Lat,
		arg.Lon,
	)
	return err
}

const upsertOrder = `-- name: UpsertOrder :exec
INSERT INTO pedido (
    id, sucursal_id, ref, folio, fecha, cliente_id,
    vendedor_ref, vendedor_codigo, vendedor_nombre, estado, requiere_domicilio,
    origen_actualizado_at, actualizado_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (sucursal_id, ref) DO UPDATE SET
    folio = EXCLUDED.folio,
    fecha = EXCLUDED.fecha,
    cliente_id = EXCLUDED.cliente_id,
    vendedor_ref = EXCLUDED.vendedor_ref,
    vendedor_codigo = EXCLUDED.vendedor_codigo,
    vendedor_nombre = EXCLUDED.vendedor_nombre,
    estado = EXCLUDED.estado,
    requiere_domicilio = EXCLUDED.requiere_domicilio,
    origen_actualizado_at = EXCLUDED.origen_actualizado_at,
    actualizado_at = now()
`

type UpsertOrderParams struct {
	ID              string
	BranchID        string
	Ref             string
	Folio           *string
	Date            time.Time
	ClientID        *string
	VendorRef       *string
	VendorCode      *string
	VendorName      *string
	Status          *string
	NeedsDelivery   bool
	SourceUpdatedAt *time.Time
}

// El pedido entra SIN trabajador: emparejar el vendedor es un paso aparte
// (LinkOrdersToSellers) que se vuelve a correr cuando alguien arregla un
// emparejamiento, sin tener que sincronizar de nuevo.
func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) error {
	_, err := q.db.Exec(ctx, upsertOrder,
		arg.ID,
		arg.BranchID,
		arg.Ref,
		arg.Folio,
		arg.Date,
		arg.ClientID,
		arg.VendorRef,
		arg.VendorCode,
		arg.VendorName,
		arg.Status,
		arg.NeedsDelivery,
		arg.SourceUpdatedAt,
	)
	return err
}

const upsertSellerLink = `-- name: UpsertSellerLink :exec
INSERT INTO vendedor_pedido (
    id, sucursal_id, trabajador_id, vendedor_codigo, vendedor_nombre, origen
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (sucursal_id, vendedor_codigo) DO UPDATE SET
    trabajador_id = CASE
        WHEN vendedor_pedido.origen = 'manual' AND EXCLUDED.origen = 'auto'
        THEN vendedor_pedido.trabajador_id ELSE EXCLUDED.trabajador_id END,
    vendedor_nombre = EXCLUDED.vendedor_nombre,
    origen = CASE
        WHEN vendedor_pedido.origen = 'manual' AND EXCLUDED.origen = 'auto'
        THEN 'manual' ELSE EXCLUDED.origen END
`

type UpsertSellerLinkParams struct {
	ID         string
	BranchID   string
	SellerID   string
	VendorCode string
	VendorName string
	Origin     string
}

// Un emparejamiento MANUAL no lo pisa el automático: si una persona ya dijo quién
// es, el algoritmo no vuelve a opinar.
func (q *Queries) UpsertSellerLink(ctx context.Context, arg UpsertSellerLinkParams) error {
	_, err := q.db.Exec(ctx, upsertSellerLink,
		arg.ID,
		arg.BranchID,
		arg.SellerID,
		arg.VendorCode,
		arg.VendorName,
		arg.Origin,
	)
	return err
}

const visitSummary = `-- name: VisitSummary :many

SELECT
    d.trabajador_id,
    d.fecha,
    count(*)::int                             AS orders,
    count(*) FILTER (WHERE v.visitado)::int   AS visited
FROM visita v
JOIN track_day d ON d.id = v.track_day_id
WHERE d.fecha BETWEEN $1::date AND $2::date
  AND ($3::text = '' OR d.sucursal_id = $3)
  AND (cardinality($4::text[]) = 0 OR d.trabajador_id = ANY ($4))
  AND ($5::text = '' OR d.trabajador_id <> $5)
GROUP BY d.trabajador_id, d.fecha
`

type VisitSummaryParams struct {
	FromDate time.Time
	ToDate   time.Time
	BranchID string
	Sellers  []string
	Exclude  string
}

type VisitSummaryRow struct {
	SellerID string
	Date     time.Time
	Orders   int32
	Visited  int32
}

// ---------------------------------------------------------------------------
// Lo que lee el panel
// ---------------------------------------------------------------------------
// Por vendedor y día: cuántos pedidos tenía y a cuántos se acercó. Es la columna
// que convierte "hizo 30 km" en "hizo la ruta".
func (q *Queries) VisitSummary(ctx context.Context, arg VisitSummaryParams) ([]VisitSummaryRow, error) {
	rows, err := q.db.Query(ctx, visitSummary,
		arg.FromDate,
		arg.ToDate,
		arg.BranchID,
		arg.Sellers,
		arg.Exclude,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VisitSummaryRow{}
	for rows.Next() {
		var i VisitSummaryRow
		if err := rows.Scan(
			&i.SellerID,
			&i.Date,
			&i.Orders,
			&i.Visited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
