// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingesta.sql

package almacen

import (
	"context"
	"time"
)

const abrirImportLog = `-- name: AbrirImportLog :one
INSERT INTO import_log (id, source_id, tipo) VALUES ($1, $2, $3) RETURNING id, source_id, tipo, inicio, fin, ficheros_vistos, ficheros_nuevos, ficheros_error, puntos_insertados, ok, detalle
`

type AbrirImportLogParams struct {
	ID       string
	SourceID *string
	Tipo     string
}

func (q *Queries) AbrirImportLog(ctx context.Context, arg AbrirImportLogParams) (ImportLog, error) {
	row := q.db.QueryRow(ctx, abrirImportLog, arg.ID, arg.SourceID, arg.Tipo)
	var i ImportLog
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Tipo,
		&i.Inicio,
		&i.Fin,
		&i.FicherosVistos,
		&i.FicherosNuevos,
		&i.FicherosError,
		&i.PuntosInsertados,
		&i.Ok,
		&i.Detalle,
	)
	return i, err
}

const actualizarCursorFuente = `-- name: ActualizarCursorFuente :exec
UPDATE drive_source
SET cursor_modificado = $2, ultimo_barrido = now(), ultimo_error = NULL, updated_at = now()
WHERE id = $1
`

type ActualizarCursorFuenteParams struct {
	ID               string
	CursorModificado *time.Time
}

func (q *Queries) ActualizarCursorFuente(ctx context.Context, arg ActualizarCursorFuenteParams) error {
	_, err := q.db.Exec(ctx, actualizarCursorFuente, arg.ID, arg.CursorModificado)
	return err
}

const aliasTodos = `-- name: AliasTodos :many
SELECT alias, trabajador_id, sucursal_id FROM device_alias
`

type AliasTodosRow struct {
	Alias        string
	TrabajadorID string
	SucursalID   *string
}

func (q *Queries) AliasTodos(ctx context.Context) ([]AliasTodosRow, error) {
	rows, err := q.db.Query(ctx, aliasTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AliasTodosRow{}
	for rows.Next() {
		var i AliasTodosRow
		if err := rows.Scan(&i.Alias, &i.TrabajadorID, &i.SucursalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const borrarParadasDeDia = `-- name: BorrarParadasDeDia :exec
DELETE FROM stop WHERE track_day_id = $1
`

func (q *Queries) BorrarParadasDeDia(ctx context.Context, trackDayID string) error {
	_, err := q.db.Exec(ctx, borrarParadasDeDia, trackDayID)
	return err
}

const borrarPuntosDeFichero = `-- name: BorrarPuntosDeFichero :exec
DELETE FROM track_point WHERE gpx_file_id = $1
`

func (q *Queries) BorrarPuntosDeFichero(ctx context.Context, gpxFileID string) error {
	_, err := q.db.Exec(ctx, borrarPuntosDeFichero, gpxFileID)
	return err
}

const cerrarImportLog = `-- name: CerrarImportLog :exec
UPDATE import_log
SET fin = now(), ficheros_vistos = $2, ficheros_nuevos = $3, ficheros_error = $4,
    puntos_insertados = $5, ok = $6, detalle = $7
WHERE id = $1
`

type CerrarImportLogParams struct {
	ID               string
	FicherosVistos   int32
	FicherosNuevos   int32
	FicherosError    int32
	PuntosInsertados int32
	Ok               bool
	Detalle          *string
}

func (q *Queries) CerrarImportLog(ctx context.Context, arg CerrarImportLogParams) error {
	_, err := q.db.Exec(ctx, cerrarImportLog,
		arg.ID,
		arg.FicherosVistos,
		arg.FicherosNuevos,
		arg.FicherosError,
		arg.PuntosInsertados,
		arg.Ok,
		arg.Detalle,
	)
	return err
}

const configDeSucursal = `-- name: ConfigDeSucursal :one
SELECT id, sucursal_id, jornada_inicio, jornada_fin, dias_laborables, parada_radio_m, parada_minutos, paso_minimo_m, sin_mov_radio_m, sin_mov_span_min, escaso_km_netos, max_velocidad_kmh, max_accuracy_m, hueco_minutos, cobertura_gap_min, cobertura_minima, tolerancia_entrada_min, tolerancia_salida_min, visita_radio_m FROM sucursal_config WHERE sucursal_id = $1
`

func (q *Queries) ConfigDeSucursal(ctx context.Context, sucursalID string) (SucursalConfig, error) {
	row := q.db.QueryRow(ctx, configDeSucursal, sucursalID)
	var i SucursalConfig
	err := row.Scan(
		&i.ID,
		&i.SucursalID,
		&i.JornadaInicio,
		&i.JornadaFin,
		&i.DiasLaborables,
		&i.ParadaRadioM,
		&i.ParadaMinutos,
		&i.PasoMinimoM,
		&i.SinMovRadioM,
		&i.SinMovSpanMin,
		&i.EscasoKmNetos,
		&i.MaxVelocidadKmh,
		&i.MaxAccuracyM,
		&i.HuecoMinutos,
		&i.CoberturaGapMin,
		&i.CoberturaMinima,
		&i.ToleranciaEntradaMin,
		&i.ToleranciaSalidaMin,
		&i.VisitaRadioM,
	)
	return i, err
}

const crearFuente = `-- name: CrearFuente :one
INSERT INTO drive_source (id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial)
VALUES ($1, $2, $3, $4::tipo_fuente, $5, $6,
        COALESCE(NULLIF($7::text, ''), 'principal'))
RETURNING id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at
`

type CrearFuenteParams struct {
	ID           string
	Nombre       string
	FolderID     string
	Tipo         TipoFuente
	SucursalID   *string
	TrabajadorID *string
	Credencial   string
}

func (q *Queries) CrearFuente(ctx context.Context, arg CrearFuenteParams) (DriveSource, error) {
	row := q.db.QueryRow(ctx, crearFuente,
		arg.ID,
		arg.Nombre,
		arg.FolderID,
		arg.Tipo,
		arg.SucursalID,
		arg.TrabajadorID,
		arg.Credencial,
	)
	var i DriveSource
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.FolderID,
		&i.Tipo,
		&i.SucursalID,
		&i.TrabajadorID,
		&i.Credencial,
		&i.Activa,
		&i.CursorModificado,
		&i.UltimoBarrido,
		&i.UltimoError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const crearParada = `-- name: CrearParada :exec
INSERT INTO stop (
    id, track_day_id, trabajador_id, sucursal_id, inicio, fin, duracion_min,
    lat, lon, radio, cliente_ref, cliente_nombre, distancia_cliente_m, seq
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CrearParadaParams struct {
	ID                string
	TrackDayID        string
	TrabajadorID      string
	SucursalID        string
	Inicio            time.Time
	Fin               time.Time
	DuracionMin       int32
	Lat               float64
	Lon               float64
	Radio             *float64
	ClienteRef        *string
	ClienteNombre     *string
	DistanciaClienteM *float64
	Seq               int32
}

func (q *Queries) CrearParada(ctx context.Context, arg CrearParadaParams) error {
	_, err := q.db.Exec(ctx, crearParada,
		arg.ID,
		arg.TrackDayID,
		arg.TrabajadorID,
		arg.SucursalID,
		arg.Inicio,
		arg.Fin,
		arg.DuracionMin,
		arg.Lat,
		arg.Lon,
		arg.Radio,
		arg.ClienteRef,
		arg.ClienteNombre,
		arg.DistanciaClienteM,
		arg.Seq,
	)
	return err
}

const crearSucursalDePrueba = `-- name: CrearSucursalDePrueba :one
INSERT INTO sucursal (id, nombre, auth_org_id) VALUES ($1, $2, $3) RETURNING id, auth_org_id, nombre, activa, timezone, created_at, updated_at
`

type CrearSucursalDePruebaParams struct {
	ID        string
	Nombre    string
	AuthOrgID *string
}

// Altas mínimas, solo para las pruebas de integración: el alta real de
// sucursales y trabajadores viene de procovar-auth, no de aquí.
func (q *Queries) CrearSucursalDePrueba(ctx context.Context, arg CrearSucursalDePruebaParams) (Sucursal, error) {
	row := q.db.QueryRow(ctx, crearSucursalDePrueba, arg.ID, arg.Nombre, arg.AuthOrgID)
	var i Sucursal
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Nombre,
		&i.Activa,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const crearTrabajadorDePrueba = `-- name: CrearTrabajadorDePrueba :one
INSERT INTO trabajador (id, nombre, sucursal_id, auth_user_id, desde)
VALUES ($1, $2, $3, $4, COALESCE($5::date, DATE '2020-01-01'))
RETURNING id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at
`

type CrearTrabajadorDePruebaParams struct {
	ID         string
	Nombre     string
	SucursalID string
	AuthUserID *string
	Desde      *time.Time
}

func (q *Queries) CrearTrabajadorDePrueba(ctx context.Context, arg CrearTrabajadorDePruebaParams) (Trabajador, error) {
	row := q.db.QueryRow(ctx, crearTrabajadorDePrueba,
		arg.ID,
		arg.Nombre,
		arg.SucursalID,
		arg.AuthUserID,
		arg.Desde,
	)
	var i Trabajador
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Nombre,
		&i.SucursalID,
		&i.EsVendedor,
		&i.Activo,
		&i.Desde,
		&i.Hasta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const feriadosDeSucursal = `-- name: FeriadosDeSucursal :many
SELECT fecha FROM feriado
WHERE sucursal_id IS NULL OR sucursal_id = $1
`

func (q *Queries) FeriadosDeSucursal(ctx context.Context, sucursalID *string) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, feriadosDeSucursal, sucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var fecha time.Time
		if err := rows.Scan(&fecha); err != nil {
			return nil, err
		}
		items = append(items, fecha)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ficheroPorDriveID = `-- name: FicheroPorDriveID :one
SELECT id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at FROM gpx_file WHERE drive_file_id = $1
`

// El "ya procesé esto" del sistema. Se consulta por las dos claves porque un
// mismo contenido puede aparecer con otro drive_file_id (copiado a otra carpeta)
// y un mismo drive_file_id puede cambiar de contenido (re-subida corregida).
func (q *Queries) FicheroPorDriveID(ctx context.Context, driveFileID string) (GpxFile, error) {
	row := q.db.QueryRow(ctx, ficheroPorDriveID, driveFileID)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Nombre,
		&i.RutaCarpeta,
		&i.TamanoBytes,
		&i.DriveCreatedAt,
		&i.Estado,
		&i.Error,
		&i.TrabajadorID,
		&i.SucursalID,
		&i.Fecha,
		&i.OrigenFecha,
		&i.PuntosTotal,
		&i.PuntosValidos,
		&i.PrimerFix,
		&i.UltimoFix,
		&i.PistaAlias,
		&i.ImportadoAt,
	)
	return i, err
}

const ficheroPorSha = `-- name: FicheroPorSha :one
SELECT id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at FROM gpx_file WHERE sha256 = $1
`

func (q *Queries) FicheroPorSha(ctx context.Context, sha256 string) (GpxFile, error) {
	row := q.db.QueryRow(ctx, ficheroPorSha, sha256)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Nombre,
		&i.RutaCarpeta,
		&i.TamanoBytes,
		&i.DriveCreatedAt,
		&i.Estado,
		&i.Error,
		&i.TrabajadorID,
		&i.SucursalID,
		&i.Fecha,
		&i.OrigenFecha,
		&i.PuntosTotal,
		&i.PuntosValidos,
		&i.PrimerFix,
		&i.UltimoFix,
		&i.PistaAlias,
		&i.ImportadoAt,
	)
	return i, err
}

const fuentePorID = `-- name: FuentePorID :one
SELECT id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at FROM drive_source WHERE id = $1
`

func (q *Queries) FuentePorID(ctx context.Context, id string) (DriveSource, error) {
	row := q.db.QueryRow(ctx, fuentePorID, id)
	var i DriveSource
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.FolderID,
		&i.Tipo,
		&i.SucursalID,
		&i.TrabajadorID,
		&i.Credencial,
		&i.Activa,
		&i.CursorModificado,
		&i.UltimoBarrido,
		&i.UltimoError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fuentesActivas = `-- name: FuentesActivas :many

SELECT id, nombre, folder_id, tipo, sucursal_id, trabajador_id, credencial, activa, cursor_modificado, ultimo_barrido, ultimo_error, created_at, updated_at FROM drive_source WHERE activa ORDER BY nombre
`

// Consultas de la ingesta: leer las carpetas, registrar ficheros y volcar puntos.
func (q *Queries) FuentesActivas(ctx context.Context) ([]DriveSource, error) {
	rows, err := q.db.Query(ctx, fuentesActivas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriveSource{}
	for rows.Next() {
		var i DriveSource
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.FolderID,
			&i.Tipo,
			&i.SucursalID,
			&i.TrabajadorID,
			&i.Credencial,
			&i.Activa,
			&i.CursorModificado,
			&i.UltimoBarrido,
			&i.UltimoError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const guardarDia = `-- name: GuardarDia :one
INSERT INTO track_day (
    id, trabajador_id, sucursal_id, fecha, estado, primer_fix, ultimo_fix,
    km_netos, min_movimiento, min_parado, cobertura, huecos, puntos,
    radio_dispersion, centroide_lat, centroide_lon, lugar_texto, banderas, gpx_file_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (trabajador_id, fecha) DO UPDATE SET
    estado = EXCLUDED.estado,
    primer_fix = EXCLUDED.primer_fix,
    ultimo_fix = EXCLUDED.ultimo_fix,
    km_netos = EXCLUDED.km_netos,
    min_movimiento = EXCLUDED.min_movimiento,
    min_parado = EXCLUDED.min_parado,
    cobertura = EXCLUDED.cobertura,
    huecos = EXCLUDED.huecos,
    puntos = EXCLUDED.puntos,
    radio_dispersion = EXCLUDED.radio_dispersion,
    centroide_lat = EXCLUDED.centroide_lat,
    centroide_lon = EXCLUDED.centroide_lon,
    lugar_texto = EXCLUDED.lugar_texto,
    banderas = EXCLUDED.banderas,
    gpx_file_id = EXCLUDED.gpx_file_id,
    calculado_at = now()
RETURNING id, trabajador_id, sucursal_id, fecha, estado, primer_fix, ultimo_fix, km_netos, min_movimiento, min_parado, cobertura, huecos, puntos, radio_dispersion, centroide_lat, centroide_lon, lugar_texto, banderas, gpx_file_id, calculado_at
`

type GuardarDiaParams struct {
	ID              string
	TrabajadorID    string
	SucursalID      string
	Fecha           time.Time
	Estado          EstadoDia
	PrimerFix       *time.Time
	UltimoFix       *time.Time
	KmNetos         float64
	MinMovimiento   int32
	MinParado       int32
	Cobertura       float64
	Huecos          int32
	Puntos          int32
	RadioDispersion *float64
	CentroideLat    *float64
	CentroideLon    *float64
	LugarTexto      *string
	Banderas        []string
	GpxFileID       *string
}

// El día se reemplaza entero en cada recálculo: es idempotente, así que
// reprocesar un fichero cuantas veces haga falta no duplica nada.
func (q *Queries) GuardarDia(ctx context.Context, arg GuardarDiaParams) (TrackDay, error) {
	row := q.db.QueryRow(ctx, guardarDia,
		arg.ID,
		arg.TrabajadorID,
		arg.SucursalID,
		arg.Fecha,
		arg.Estado,
		arg.PrimerFix,
		arg.UltimoFix,
		arg.KmNetos,
		arg.MinMovimiento,
		arg.MinParado,
		arg.Cobertura,
		arg.Huecos,
		arg.Puntos,
		arg.RadioDispersion,
		arg.CentroideLat,
		arg.CentroideLon,
		arg.LugarTexto,
		arg.Banderas,
		arg.GpxFileID,
	)
	var i TrackDay
	err := row.Scan(
		&i.ID,
		&i.TrabajadorID,
		&i.SucursalID,
		&i.Fecha,
		&i.Estado,
		&i.PrimerFix,
		&i.UltimoFix,
		&i.KmNetos,
		&i.MinMovimiento,
		&i.MinParado,
		&i.Cobertura,
		&i.Huecos,
		&i.Puntos,
		&i.RadioDispersion,
		&i.CentroideLat,
		&i.CentroideLon,
		&i.LugarTexto,
		&i.Banderas,
		&i.GpxFileID,
		&i.CalculadoAt,
	)
	return i, err
}

const guardarFichero = `-- name: GuardarFichero :one
INSERT INTO gpx_file (
    id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes,
    drive_created_at, estado, error, trabajador_id, sucursal_id, fecha,
    origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (drive_file_id) DO UPDATE SET
    sha256 = EXCLUDED.sha256,
    nombre = EXCLUDED.nombre,
    ruta_carpeta = EXCLUDED.ruta_carpeta,
    tamano_bytes = EXCLUDED.tamano_bytes,
    estado = EXCLUDED.estado,
    error = EXCLUDED.error,
    trabajador_id = EXCLUDED.trabajador_id,
    sucursal_id = EXCLUDED.sucursal_id,
    fecha = EXCLUDED.fecha,
    origen_fecha = EXCLUDED.origen_fecha,
    puntos_total = EXCLUDED.puntos_total,
    puntos_validos = EXCLUDED.puntos_validos,
    primer_fix = EXCLUDED.primer_fix,
    ultimo_fix = EXCLUDED.ultimo_fix,
    pista_alias = EXCLUDED.pista_alias,
    importado_at = now()
RETURNING id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at
`

type GuardarFicheroParams struct {
	ID             string
	SourceID       string
	DriveFileID    string
	Sha256         string
	Nombre         string
	RutaCarpeta    *string
	TamanoBytes    *int32
	DriveCreatedAt *time.Time
	Estado         EstadoFichero
	Error          *string
	TrabajadorID   *string
	SucursalID     *string
	Fecha          *time.Time
	OrigenFecha    OrigenFecha
	PuntosTotal    int32
	PuntosValidos  int32
	PrimerFix      *time.Time
	UltimoFix      *time.Time
	PistaAlias     *string
}

func (q *Queries) GuardarFichero(ctx context.Context, arg GuardarFicheroParams) (GpxFile, error) {
	row := q.db.QueryRow(ctx, guardarFichero,
		arg.ID,
		arg.SourceID,
		arg.DriveFileID,
		arg.Sha256,
		arg.Nombre,
		arg.RutaCarpeta,
		arg.TamanoBytes,
		arg.DriveCreatedAt,
		arg.Estado,
		arg.Error,
		arg.TrabajadorID,
		arg.SucursalID,
		arg.Fecha,
		arg.OrigenFecha,
		arg.PuntosTotal,
		arg.PuntosValidos,
		arg.PrimerFix,
		arg.UltimoFix,
		arg.PistaAlias,
	)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Nombre,
		&i.RutaCarpeta,
		&i.TamanoBytes,
		&i.DriveCreatedAt,
		&i.Estado,
		&i.Error,
		&i.TrabajadorID,
		&i.SucursalID,
		&i.Fecha,
		&i.OrigenFecha,
		&i.PuntosTotal,
		&i.PuntosValidos,
		&i.PrimerFix,
		&i.UltimoFix,
		&i.PistaAlias,
		&i.ImportadoAt,
	)
	return i, err
}

const marcarAusencias = `-- name: MarcarAusencias :execrows
INSERT INTO track_day (id, trabajador_id, sucursal_id, fecha, estado)
SELECT
    md5(t.id || ':' || to_char($1::date, 'YYYY-MM-DD')),
    t.id,
    t.sucursal_id,
    $1::date,
    'SIN_FICHERO'
FROM trabajador t
WHERE t.activo
  AND t.es_vendedor
  AND t.desde <= $1::date
  AND (t.hasta IS NULL OR t.hasta >= $1::date)
  AND ($2::text = '' OR t.sucursal_id = $2)
ON CONFLICT (trabajador_id, fecha) DO NOTHING
`

type MarcarAusenciasParams struct {
	Fecha      time.Time
	SucursalID string
}

// Marca las ausencias del día laborable: cada vendedor activo sin fila queda en
// SIN_FICHERO. Sin esto, "no subió nada" sería la ausencia de una fila, y las
// ausencias no se pueden listar, ni contar, ni ordenar por número de faltas.
func (q *Queries) MarcarAusencias(ctx context.Context, arg MarcarAusenciasParams) (int64, error) {
	result, err := q.db.Exec(ctx, marcarAusencias, arg.Fecha, arg.SucursalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const marcarErrorFuente = `-- name: MarcarErrorFuente :exec
UPDATE drive_source
SET ultimo_barrido = now(), ultimo_error = $2, updated_at = now()
WHERE id = $1
`

type MarcarErrorFuenteParams struct {
	ID          string
	UltimoError *string
}

func (q *Queries) MarcarErrorFuente(ctx context.Context, arg MarcarErrorFuenteParams) error {
	_, err := q.db.Exec(ctx, marcarErrorFuente, arg.ID, arg.UltimoError)
	return err
}

const puntosDeTrabajadorEnFecha = `-- name: PuntosDeTrabajadorEnFecha :many
SELECT p.ts, p.lat, p.lon, p.accuracy, p.seq
FROM track_point p
WHERE p.trabajador_id = $1
  AND p.ts IS NOT NULL
  AND (p.ts AT TIME ZONE $2::text)::date = $3::date
ORDER BY p.ts
`

type PuntosDeTrabajadorEnFechaParams struct {
	TrabajadorID *string
	Zona         string
	Fecha        time.Time
}

type PuntosDeTrabajadorEnFechaRow struct {
	Ts       *time.Time
	Lat      float64
	Lon      float64
	Accuracy *float64
	Seq      int32
}

// Todos los puntos de un vendedor en un día local, vengan del fichero que
// vengan: el día se recalcula desde la base y no desde el fichero recién
// llegado, porque puede haber varios ficheros para el mismo día (una sesión de
// mañana y otra de tarde) y sumarlos por separado daría dos veredictos.
func (q *Queries) PuntosDeTrabajadorEnFecha(ctx context.Context, arg PuntosDeTrabajadorEnFechaParams) ([]PuntosDeTrabajadorEnFechaRow, error) {
	rows, err := q.db.Query(ctx, puntosDeTrabajadorEnFecha, arg.TrabajadorID, arg.Zona, arg.Fecha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PuntosDeTrabajadorEnFechaRow{}
	for rows.Next() {
		var i PuntosDeTrabajadorEnFechaRow
		if err := rows.Scan(
			&i.Ts,
			&i.Lat,
			&i.Lon,
			&i.Accuracy,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sucursalPorID = `-- name: SucursalPorID :one
SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at FROM sucursal WHERE id = $1
`

func (q *Queries) SucursalPorID(ctx context.Context, id string) (Sucursal, error) {
	row := q.db.QueryRow(ctx, sucursalPorID, id)
	var i Sucursal
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Nombre,
		&i.Activa,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sucursalesActivas = `-- name: SucursalesActivas :many
SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at FROM sucursal WHERE activa ORDER BY nombre
`

func (q *Queries) SucursalesActivas(ctx context.Context) ([]Sucursal, error) {
	rows, err := q.db.Query(ctx, sucursalesActivas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sucursal{}
	for rows.Next() {
		var i Sucursal
		if err := rows.Scan(
			&i.ID,
			&i.AuthOrgID,
			&i.Nombre,
			&i.Activa,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trabajadorPorID = `-- name: TrabajadorPorID :one
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE id = $1
`

func (q *Queries) TrabajadorPorID(ctx context.Context, id string) (Trabajador, error) {
	row := q.db.QueryRow(ctx, trabajadorPorID, id)
	var i Trabajador
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Nombre,
		&i.SucursalID,
		&i.EsVendedor,
		&i.Activo,
		&i.Desde,
		&i.Hasta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trabajadoresActivos = `-- name: TrabajadoresActivos :many
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE activo ORDER BY nombre
`

func (q *Queries) TrabajadoresActivos(ctx context.Context) ([]Trabajador, error) {
	rows, err := q.db.Query(ctx, trabajadoresActivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trabajador{}
	for rows.Next() {
		var i Trabajador
		if err := rows.Scan(
			&i.ID,
			&i.AuthUserID,
			&i.Nombre,
			&i.SucursalID,
			&i.EsVendedor,
			&i.Activo,
			&i.Desde,
			&i.Hasta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
