// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package almacen

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type CalidadPunto string

const (
	CalidadPuntoOK        CalidadPunto = "OK"
	CalidadPuntoSALTO     CalidadPunto = "SALTO"
	CalidadPuntoIMPRECISO CalidadPunto = "IMPRECISO"
	CalidadPuntoDUPLICADO CalidadPunto = "DUPLICADO"
	CalidadPuntoSINHORA   CalidadPunto = "SIN_HORA"
)

func (e *CalidadPunto) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CalidadPunto(s)
	case string:
		*e = CalidadPunto(s)
	default:
		return fmt.Errorf("unsupported scan type for CalidadPunto: %T", src)
	}
	return nil
}

type NullCalidadPunto struct {
	CalidadPunto CalidadPunto
	Valid        bool // Valid is true if CalidadPunto is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCalidadPunto) Scan(value interface{}) error {
	if value == nil {
		ns.CalidadPunto, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CalidadPunto.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCalidadPunto) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CalidadPunto), nil
}

type EstadoDia string

const (
	EstadoDiaOK               EstadoDia = "OK"
	EstadoDiaSINFICHERO       EstadoDia = "SIN_FICHERO"
	EstadoDiaSINFECHA         EstadoDia = "SIN_FECHA"
	EstadoDiaSINMOVIMIENTO    EstadoDia = "SIN_MOVIMIENTO"
	EstadoDiaMOVIMIENTOESCASO EstadoDia = "MOVIMIENTO_ESCASO"
	EstadoDiaNOLABORABLE      EstadoDia = "NO_LABORABLE"
)

func (e *EstadoDia) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoDia(s)
	case string:
		*e = EstadoDia(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoDia: %T", src)
	}
	return nil
}

type NullEstadoDia struct {
	EstadoDia EstadoDia
	Valid     bool // Valid is true if EstadoDia is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoDia) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoDia, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoDia.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoDia) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoDia), nil
}

type EstadoFichero string

const (
	EstadoFicheroPROCESADO  EstadoFichero = "PROCESADO"
	EstadoFicheroSINASIGNAR EstadoFichero = "SIN_ASIGNAR"
	EstadoFicheroSINFECHA   EstadoFichero = "SIN_FECHA"
	EstadoFicheroERROR      EstadoFichero = "ERROR"
)

func (e *EstadoFichero) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoFichero(s)
	case string:
		*e = EstadoFichero(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoFichero: %T", src)
	}
	return nil
}

type NullEstadoFichero struct {
	EstadoFichero EstadoFichero
	Valid         bool // Valid is true if EstadoFichero is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoFichero) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoFichero, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoFichero.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoFichero) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoFichero), nil
}

type OrigenFecha string

const (
	OrigenFechaPUNTOS  OrigenFecha = "PUNTOS"
	OrigenFechaNOMBRE  OrigenFecha = "NOMBRE"
	OrigenFechaDRIVE   OrigenFecha = "DRIVE"
	OrigenFechaNINGUNO OrigenFecha = "NINGUNO"
)

func (e *OrigenFecha) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrigenFecha(s)
	case string:
		*e = OrigenFecha(s)
	default:
		return fmt.Errorf("unsupported scan type for OrigenFecha: %T", src)
	}
	return nil
}

type NullOrigenFecha struct {
	OrigenFecha OrigenFecha
	Valid       bool // Valid is true if OrigenFecha is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrigenFecha) Scan(value interface{}) error {
	if value == nil {
		ns.OrigenFecha, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrigenFecha.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrigenFecha) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrigenFecha), nil
}

type TipoFuente string

const (
	TipoFuenteSUCURSAL TipoFuente = "SUCURSAL"
	TipoFuenteVENDEDOR TipoFuente = "VENDEDOR"
	TipoFuenteMIXTA    TipoFuente = "MIXTA"
)

func (e *TipoFuente) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoFuente(s)
	case string:
		*e = TipoFuente(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoFuente: %T", src)
	}
	return nil
}

type NullTipoFuente struct {
	TipoFuente TipoFuente
	Valid      bool // Valid is true if TipoFuente is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoFuente) Scan(value interface{}) error {
	if value == nil {
		ns.TipoFuente, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoFuente.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoFuente) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoFuente), nil
}

type DeviceAlias struct {
	ID            string
	Alias         string
	AliasOriginal string
	TrabajadorID  string
	SucursalID    *string
	CreatedAt     time.Time
	CreatedBy     *string
}

type DriveSource struct {
	ID               string
	Nombre           string
	FolderID         string
	Tipo             TipoFuente
	SucursalID       *string
	TrabajadorID     *string
	Credencial       string
	Activa           bool
	CursorModificado *time.Time
	UltimoBarrido    *time.Time
	UltimoError      *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Feriado struct {
	ID         string
	Fecha      time.Time
	Nombre     string
	SucursalID *string
}

type GpxFile struct {
	ID             string
	SourceID       string
	DriveFileID    string
	Sha256         string
	Nombre         string
	RutaCarpeta    *string
	TamanoBytes    *int32
	DriveCreatedAt *time.Time
	Estado         EstadoFichero
	Error          *string
	TrabajadorID   *string
	SucursalID     *string
	Fecha          *time.Time
	OrigenFecha    OrigenFecha
	PuntosTotal    int32
	PuntosValidos  int32
	PrimerFix      *time.Time
	UltimoFix      *time.Time
	PistaAlias     *string
	ImportadoAt    time.Time
}

type ImportLog struct {
	ID               string
	SourceID         *string
	Tipo             string
	Inicio           time.Time
	Fin              *time.Time
	FicherosVistos   int32
	FicherosNuevos   int32
	FicherosError    int32
	PuntosInsertados int32
	Ok               bool
	Detalle          *string
}

type Stop struct {
	ID                string
	TrackDayID        string
	TrabajadorID      string
	SucursalID        string
	Inicio            time.Time
	Fin               time.Time
	DuracionMin       int32
	Lat               float64
	Lon               float64
	Radio             *float64
	ClienteRef        *string
	ClienteNombre     *string
	DistanciaClienteM *float64
	Seq               int32
}

type Sucursal struct {
	ID        string
	AuthOrgID *string
	Nombre    string
	Activa    bool
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SucursalConfig struct {
	ID                   string
	SucursalID           string
	JornadaInicio        string
	JornadaFin           string
	DiasLaborables       []int32
	ParadaRadioM         int32
	ParadaMinutos        int32
	PasoMinimoM          int32
	SinMovRadioM         int32
	SinMovSpanMin        int32
	EscasoKmNetos        float64
	MaxVelocidadKmh      int32
	MaxAccuracyM         int32
	HuecoMinutos         int32
	CoberturaGapMin      int32
	CoberturaMinima      float64
	ToleranciaEntradaMin int32
	ToleranciaSalidaMin  int32
	VisitaRadioM         int32
}

type Supervision struct {
	ID           string
	GestorID     string
	SupervisorID string
	Desde        time.Time
	Hasta        *time.Time
	CreatedAt    time.Time
}

type Trabajador struct {
	ID         string
	AuthUserID *string
	Nombre     string
	SucursalID string
	EsVendedor bool
	Activo     bool
	Desde      time.Time
	Hasta      *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TrackDay struct {
	ID              string
	TrabajadorID    string
	SucursalID      string
	Fecha           time.Time
	Estado          EstadoDia
	PrimerFix       *time.Time
	UltimoFix       *time.Time
	KmNetos         float64
	MinMovimiento   int32
	MinParado       int32
	Cobertura       float64
	Huecos          int32
	Puntos          int32
	RadioDispersion *float64
	CentroideLat    *float64
	CentroideLon    *float64
	LugarTexto      *string
	Banderas        []string
	GpxFileID       *string
	CalculadoAt     time.Time
}

type TrackPoint struct {
	ID           int64
	GpxFileID    string
	TrabajadorID *string
	SucursalID   *string
	Ts           *time.Time
	Lat          float64
	Lon          float64
	Ele          *float64
	Speed        *float64
	Accuracy     *float64
	Seq          int32
	Quality      CalidadPunto
}
