// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: panel.sql

package almacen

import (
	"context"
	"time"
)

const aliasDeSucursal = `-- name: AliasDeSucursal :many
SELECT a.id, a.alias, a.alias_original, a.trabajador_id, a.sucursal_id, a.created_at, a.created_by, t.nombre AS trabajador
FROM device_alias a
JOIN trabajador t ON t.id = a.trabajador_id
WHERE $1::text = '' OR a.sucursal_id = $1
ORDER BY a.alias_original
`

type AliasDeSucursalRow struct {
	ID            string
	Alias         string
	AliasOriginal string
	TrabajadorID  string
	SucursalID    *string
	CreatedAt     time.Time
	CreatedBy     *string
	Trabajador    string
}

func (q *Queries) AliasDeSucursal(ctx context.Context, sucursalID string) ([]AliasDeSucursalRow, error) {
	rows, err := q.db.Query(ctx, aliasDeSucursal, sucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AliasDeSucursalRow{}
	for rows.Next() {
		var i AliasDeSucursalRow
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.AliasOriginal,
			&i.TrabajadorID,
			&i.SucursalID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Trabajador,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const asignarFichero = `-- name: AsignarFichero :one
UPDATE gpx_file
SET trabajador_id = $1,
    sucursal_id = $2,
    fecha = coalesce($3::date, fecha),
    estado = CASE WHEN coalesce($3::date, fecha) IS NULL THEN 'SIN_FECHA'::estado_fichero
                  ELSE 'PROCESADO'::estado_fichero END
WHERE id = $4
RETURNING id, source_id, drive_file_id, sha256, nombre, ruta_carpeta, tamano_bytes, drive_created_at, estado, error, trabajador_id, sucursal_id, fecha, origen_fecha, puntos_total, puntos_validos, primer_fix, ultimo_fix, pista_alias, importado_at
`

type AsignarFicheroParams struct {
	TrabajadorID *string
	SucursalID   *string
	Fecha        *time.Time
	ID           string
}

func (q *Queries) AsignarFichero(ctx context.Context, arg AsignarFicheroParams) (GpxFile, error) {
	row := q.db.QueryRow(ctx, asignarFichero,
		arg.TrabajadorID,
		arg.SucursalID,
		arg.Fecha,
		arg.ID,
	)
	var i GpxFile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DriveFileID,
		&i.Sha256,
		&i.Nombre,
		&i.RutaCarpeta,
		&i.TamanoBytes,
		&i.DriveCreatedAt,
		&i.Estado,
		&i.Error,
		&i.TrabajadorID,
		&i.SucursalID,
		&i.Fecha,
		&i.OrigenFecha,
		&i.PuntosTotal,
		&i.PuntosValidos,
		&i.PrimerFix,
		&i.UltimoFix,
		&i.PistaAlias,
		&i.ImportadoAt,
	)
	return i, err
}

const bandeja = `-- name: Bandeja :many
SELECT f.id, f.source_id, f.drive_file_id, f.sha256, f.nombre, f.ruta_carpeta, f.tamano_bytes, f.drive_created_at, f.estado, f.error, f.trabajador_id, f.sucursal_id, f.fecha, f.origen_fecha, f.puntos_total, f.puntos_validos, f.primer_fix, f.ultimo_fix, f.pista_alias, f.importado_at, s.nombre AS fuente
FROM gpx_file f
JOIN drive_source s ON s.id = f.source_id
WHERE f.estado IN ('SIN_ASIGNAR', 'SIN_FECHA', 'ERROR')
  AND ($1::text = '' OR f.sucursal_id IS NULL OR f.sucursal_id = $1)
ORDER BY f.importado_at DESC
LIMIT $2
`

type BandejaParams struct {
	SucursalID string
	Limite     int32
}

type BandejaRow struct {
	ID             string
	SourceID       string
	DriveFileID    string
	Sha256         string
	Nombre         string
	RutaCarpeta    *string
	TamanoBytes    *int32
	DriveCreatedAt *time.Time
	Estado         EstadoFichero
	Error          *string
	TrabajadorID   *string
	SucursalID     *string
	Fecha          *time.Time
	OrigenFecha    OrigenFecha
	PuntosTotal    int32
	PuntosValidos  int32
	PrimerFix      *time.Time
	UltimoFix      *time.Time
	PistaAlias     *string
	ImportadoAt    time.Time
	Fuente         string
}

// La bandeja: lo que la ingesta no supo asignar o fechar. Es lo que evita que un
// fichero se pierda en silencio.
func (q *Queries) Bandeja(ctx context.Context, arg BandejaParams) ([]BandejaRow, error) {
	rows, err := q.db.Query(ctx, bandeja, arg.SucursalID, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BandejaRow{}
	for rows.Next() {
		var i BandejaRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DriveFileID,
			&i.Sha256,
			&i.Nombre,
			&i.RutaCarpeta,
			&i.TamanoBytes,
			&i.DriveCreatedAt,
			&i.Estado,
			&i.Error,
			&i.TrabajadorID,
			&i.SucursalID,
			&i.Fecha,
			&i.OrigenFecha,
			&i.PuntosTotal,
			&i.PuntosValidos,
			&i.PrimerFix,
			&i.UltimoFix,
			&i.PistaAlias,
			&i.ImportadoAt,
			&i.Fuente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const borrarAlias = `-- name: BorrarAlias :exec
DELETE FROM device_alias WHERE id = $1
`

func (q *Queries) BorrarAlias(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, borrarAlias, id)
	return err
}

const calendario = `-- name: Calendario :many

SELECT
    d.trabajador_id,
    t.nombre AS trabajador,
    d.sucursal_id,
    d.fecha,
    d.estado,
    d.km_netos,
    d.cobertura,
    d.primer_fix,
    d.ultimo_fix,
    d.banderas,
    d.radio_dispersion,
    d.lugar_texto
FROM track_day d
JOIN trabajador t ON t.id = d.trabajador_id
WHERE d.fecha BETWEEN $1::date AND $2::date
  AND ($3::text = '' OR d.sucursal_id = $3)
  AND (cardinality($4::text[]) = 0 OR d.trabajador_id = ANY ($4))
  AND ($5::text = '' OR d.trabajador_id <> $5)
ORDER BY t.nombre, d.fecha
`

type CalendarioParams struct {
	Desde        time.Time
	Hasta        time.Time
	SucursalID   string
	Trabajadores []string
	Excluir      string
}

type CalendarioRow struct {
	TrabajadorID    string
	Trabajador      string
	SucursalID      string
	Fecha           time.Time
	Estado          EstadoDia
	KmNetos         float64
	Cobertura       float64
	PrimerFix       *time.Time
	UltimoFix       *time.Time
	Banderas        []string
	RadioDispersion *float64
	LugarTexto      *string
}

// Consultas del panel. Todas llevan EL MISMO bloque de alcance:
//
//	(@sucursal_id = ''  OR sucursal_id = @sucursal_id)
//	(cardinality(@trabajadores) = 0 OR trabajador_id = ANY(@trabajadores))
//	(@excluir = ''      OR trabajador_id <> @excluir)
//
// que es la traducción literal de internal/alcance.Filtro. Se repite en el SQL
// porque no hay otra forma con sqlc, pero NINGUNA consulta lo construye por su
// cuenta: los tres parámetros salen siempre de alcance.Calcular. El día que se
// escriba una consulta nueva sin ellos, la revisión debería rechazarla.
// El calendario de cumplimiento: la cuadrícula de vendedores × días laborables.
func (q *Queries) Calendario(ctx context.Context, arg CalendarioParams) ([]CalendarioRow, error) {
	rows, err := q.db.Query(ctx, calendario,
		arg.Desde,
		arg.Hasta,
		arg.SucursalID,
		arg.Trabajadores,
		arg.Excluir,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarioRow{}
	for rows.Next() {
		var i CalendarioRow
		if err := rows.Scan(
			&i.TrabajadorID,
			&i.Trabajador,
			&i.SucursalID,
			&i.Fecha,
			&i.Estado,
			&i.KmNetos,
			&i.Cobertura,
			&i.PrimerFix,
			&i.UltimoFix,
			&i.Banderas,
			&i.RadioDispersion,
			&i.LugarTexto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const crearAlias = `-- name: CrearAlias :one
INSERT INTO device_alias (id, alias, alias_original, trabajador_id, sucursal_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (alias) DO UPDATE SET
    trabajador_id = EXCLUDED.trabajador_id,
    sucursal_id = EXCLUDED.sucursal_id
RETURNING id, alias, alias_original, trabajador_id, sucursal_id, created_at, created_by
`

type CrearAliasParams struct {
	ID            string
	Alias         string
	AliasOriginal string
	TrabajadorID  string
	SucursalID    *string
	CreatedBy     *string
}

func (q *Queries) CrearAlias(ctx context.Context, arg CrearAliasParams) (DeviceAlias, error) {
	row := q.db.QueryRow(ctx, crearAlias,
		arg.ID,
		arg.Alias,
		arg.AliasOriginal,
		arg.TrabajadorID,
		arg.SucursalID,
		arg.CreatedBy,
	)
	var i DeviceAlias
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.AliasOriginal,
		&i.TrabajadorID,
		&i.SucursalID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const diaDeTrabajador = `-- name: DiaDeTrabajador :one
SELECT d.id, d.trabajador_id, d.sucursal_id, d.fecha, d.estado, d.primer_fix, d.ultimo_fix, d.km_netos, d.min_movimiento, d.min_parado, d.cobertura, d.huecos, d.puntos, d.radio_dispersion, d.centroide_lat, d.centroide_lon, d.lugar_texto, d.banderas, d.gpx_file_id, d.calculado_at, t.nombre AS trabajador
FROM track_day d
JOIN trabajador t ON t.id = d.trabajador_id
WHERE d.trabajador_id = $1 AND d.fecha = $2::date
  AND ($3::text = '' OR d.sucursal_id = $3)
  AND (cardinality($4::text[]) = 0 OR d.trabajador_id = ANY ($4))
  AND ($5::text = '' OR d.trabajador_id <> $5)
`

type DiaDeTrabajadorParams struct {
	TrabajadorID string
	Fecha        time.Time
	SucursalID   string
	Trabajadores []string
	Excluir      string
}

type DiaDeTrabajadorRow struct {
	ID              string
	TrabajadorID    string
	SucursalID      string
	Fecha           time.Time
	Estado          EstadoDia
	PrimerFix       *time.Time
	UltimoFix       *time.Time
	KmNetos         float64
	MinMovimiento   int32
	MinParado       int32
	Cobertura       float64
	Huecos          int32
	Puntos          int32
	RadioDispersion *float64
	CentroideLat    *float64
	CentroideLon    *float64
	LugarTexto      *string
	Banderas        []string
	GpxFileID       *string
	CalculadoAt     time.Time
	Trabajador      string
}

func (q *Queries) DiaDeTrabajador(ctx context.Context, arg DiaDeTrabajadorParams) (DiaDeTrabajadorRow, error) {
	row := q.db.QueryRow(ctx, diaDeTrabajador,
		arg.TrabajadorID,
		arg.Fecha,
		arg.SucursalID,
		arg.Trabajadores,
		arg.Excluir,
	)
	var i DiaDeTrabajadorRow
	err := row.Scan(
		&i.ID,
		&i.TrabajadorID,
		&i.SucursalID,
		&i.Fecha,
		&i.Estado,
		&i.PrimerFix,
		&i.UltimoFix,
		&i.KmNetos,
		&i.MinMovimiento,
		&i.MinParado,
		&i.Cobertura,
		&i.Huecos,
		&i.Puntos,
		&i.RadioDispersion,
		&i.CentroideLat,
		&i.CentroideLon,
		&i.LugarTexto,
		&i.Banderas,
		&i.GpxFileID,
		&i.CalculadoAt,
		&i.Trabajador,
	)
	return i, err
}

const paradasDeDia = `-- name: ParadasDeDia :many
SELECT id, track_day_id, trabajador_id, sucursal_id, inicio, fin, duracion_min, lat, lon, radio, cliente_ref, cliente_nombre, distancia_cliente_m, seq FROM stop WHERE track_day_id = $1 ORDER BY seq
`

func (q *Queries) ParadasDeDia(ctx context.Context, trackDayID string) ([]Stop, error) {
	rows, err := q.db.Query(ctx, paradasDeDia, trackDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stop{}
	for rows.Next() {
		var i Stop
		if err := rows.Scan(
			&i.ID,
			&i.TrackDayID,
			&i.TrabajadorID,
			&i.SucursalID,
			&i.Inicio,
			&i.Fin,
			&i.DuracionMin,
			&i.Lat,
			&i.Lon,
			&i.Radio,
			&i.ClienteRef,
			&i.ClienteNombre,
			&i.DistanciaClienteM,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const puntosDeDia = `-- name: PuntosDeDia :many
SELECT p.ts, p.lat, p.lon, p.ele, p.speed, p.quality, p.seq
FROM track_point p
JOIN track_day d ON d.trabajador_id = p.trabajador_id
                AND d.fecha = (p.ts AT TIME ZONE $1::text)::date
WHERE d.id = $2
  AND p.ts IS NOT NULL
  AND to_char(p.ts AT TIME ZONE $1::text, 'HH24:MI') BETWEEN $3::text AND $4::text
ORDER BY p.ts
`

type PuntosDeDiaParams struct {
	Zona          string
	TrackDayID    string
	JornadaInicio string
	JornadaFin    string
}

type PuntosDeDiaRow struct {
	Ts      *time.Time
	Lat     float64
	Lon     float64
	Ele     *float64
	Speed   *float64
	Quality CalidadPunto
	Seq     int32
}

// Los puntos que pinta el visor. Solo la jornada por defecto; el interruptor de
// "día completo" manda @jornada_inicio = '00:00' y @jornada_fin = '23:59'.
func (q *Queries) PuntosDeDia(ctx context.Context, arg PuntosDeDiaParams) ([]PuntosDeDiaRow, error) {
	rows, err := q.db.Query(ctx, puntosDeDia,
		arg.Zona,
		arg.TrackDayID,
		arg.JornadaInicio,
		arg.JornadaFin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PuntosDeDiaRow{}
	for rows.Next() {
		var i PuntosDeDiaRow
		if err := rows.Scan(
			&i.Ts,
			&i.Lat,
			&i.Lon,
			&i.Ele,
			&i.Speed,
			&i.Quality,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const puntosDeFichero = `-- name: PuntosDeFichero :many
SELECT p.ts, p.lat, p.lon, p.ele, p.speed, p.quality, p.seq
FROM track_point p
WHERE p.gpx_file_id = $1
ORDER BY p.seq
`

type PuntosDeFicheroRow struct {
	Ts      *time.Time
	Lat     float64
	Lon     float64
	Ele     *float64
	Speed   *float64
	Quality CalidadPunto
	Seq     int32
}

// Un fichero sin horas no casa con la consulta anterior (no tiene ts), pero su
// recorrido sí se puede pintar: para eso están estos puntos, por orden de
// secuencia.
func (q *Queries) PuntosDeFichero(ctx context.Context, gpxFileID string) ([]PuntosDeFicheroRow, error) {
	rows, err := q.db.Query(ctx, puntosDeFichero, gpxFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PuntosDeFicheroRow{}
	for rows.Next() {
		var i PuntosDeFicheroRow
		if err := rows.Scan(
			&i.Ts,
			&i.Lat,
			&i.Lon,
			&i.Ele,
			&i.Speed,
			&i.Quality,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumenIncidencias = `-- name: ResumenIncidencias :many
SELECT
    d.trabajador_id,
    t.nombre AS trabajador,
    count(*) FILTER (WHERE d.estado = 'SIN_FICHERO')    AS sin_fichero,
    count(*) FILTER (WHERE d.estado = 'SIN_FECHA')      AS sin_fecha,
    count(*) FILTER (WHERE d.estado = 'SIN_MOVIMIENTO') AS sin_movimiento,
    count(*) FILTER (WHERE d.estado = 'OK')             AS dias_ok,
    coalesce(sum(d.km_netos), 0)::float8                AS km_total
FROM track_day d
JOIN trabajador t ON t.id = d.trabajador_id
WHERE d.fecha BETWEEN $1::date AND $2::date
  AND d.estado <> 'NO_LABORABLE'
  AND ($3::text = '' OR d.sucursal_id = $3)
  AND (cardinality($4::text[]) = 0 OR d.trabajador_id = ANY ($4))
  AND ($5::text = '' OR d.trabajador_id <> $5)
GROUP BY d.trabajador_id, t.nombre
ORDER BY sin_fichero + sin_fecha + sin_movimiento DESC, t.nombre
`

type ResumenIncidenciasParams struct {
	Desde        time.Time
	Hasta        time.Time
	SucursalID   string
	Trabajadores []string
	Excluir      string
}

type ResumenIncidenciasRow struct {
	TrabajadorID  string
	Trabajador    string
	SinFichero    int64
	SinFecha      int64
	SinMovimiento int64
	DiasOk        int64
	KmTotal       float64
}

func (q *Queries) ResumenIncidencias(ctx context.Context, arg ResumenIncidenciasParams) ([]ResumenIncidenciasRow, error) {
	rows, err := q.db.Query(ctx, resumenIncidencias,
		arg.Desde,
		arg.Hasta,
		arg.SucursalID,
		arg.Trabajadores,
		arg.Excluir,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResumenIncidenciasRow{}
	for rows.Next() {
		var i ResumenIncidenciasRow
		if err := rows.Scan(
			&i.TrabajadorID,
			&i.Trabajador,
			&i.SinFichero,
			&i.SinFecha,
			&i.SinMovimiento,
			&i.DiasOk,
			&i.KmTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const semanaDeTrabajador = `-- name: SemanaDeTrabajador :many
SELECT d.id, d.trabajador_id, d.sucursal_id, d.fecha, d.estado, d.primer_fix, d.ultimo_fix, d.km_netos, d.min_movimiento, d.min_parado, d.cobertura, d.huecos, d.puntos, d.radio_dispersion, d.centroide_lat, d.centroide_lon, d.lugar_texto, d.banderas, d.gpx_file_id, d.calculado_at
FROM track_day d
WHERE d.trabajador_id = $1
  AND d.fecha BETWEEN $2::date AND $3::date
  AND ($4::text = '' OR d.sucursal_id = $4)
  AND (cardinality($5::text[]) = 0 OR d.trabajador_id = ANY ($5))
  AND ($6::text = '' OR d.trabajador_id <> $6)
ORDER BY d.fecha
`

type SemanaDeTrabajadorParams struct {
	TrabajadorID string
	Desde        time.Time
	Hasta        time.Time
	SucursalID   string
	Trabajadores []string
	Excluir      string
}

func (q *Queries) SemanaDeTrabajador(ctx context.Context, arg SemanaDeTrabajadorParams) ([]TrackDay, error) {
	rows, err := q.db.Query(ctx, semanaDeTrabajador,
		arg.TrabajadorID,
		arg.Desde,
		arg.Hasta,
		arg.SucursalID,
		arg.Trabajadores,
		arg.Excluir,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackDay{}
	for rows.Next() {
		var i TrackDay
		if err := rows.Scan(
			&i.ID,
			&i.TrabajadorID,
			&i.SucursalID,
			&i.Fecha,
			&i.Estado,
			&i.PrimerFix,
			&i.UltimoFix,
			&i.KmNetos,
			&i.MinMovimiento,
			&i.MinParado,
			&i.Cobertura,
			&i.Huecos,
			&i.Puntos,
			&i.RadioDispersion,
			&i.CentroideLat,
			&i.CentroideLon,
			&i.LugarTexto,
			&i.Banderas,
			&i.GpxFileID,
			&i.CalculadoAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sucursalPorAuthOrg = `-- name: SucursalPorAuthOrg :one
SELECT id, auth_org_id, nombre, activa, timezone, created_at, updated_at FROM sucursal WHERE auth_org_id = $1
`

func (q *Queries) SucursalPorAuthOrg(ctx context.Context, authOrgID *string) (Sucursal, error) {
	row := q.db.QueryRow(ctx, sucursalPorAuthOrg, authOrgID)
	var i Sucursal
	err := row.Scan(
		&i.ID,
		&i.AuthOrgID,
		&i.Nombre,
		&i.Activa,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trabajadorPorAuthID = `-- name: TrabajadorPorAuthID :one
SELECT id, auth_user_id, nombre, sucursal_id, es_vendedor, activo, desde, hasta, created_at, updated_at FROM trabajador WHERE auth_user_id = $1
`

func (q *Queries) TrabajadorPorAuthID(ctx context.Context, authUserID *string) (Trabajador, error) {
	row := q.db.QueryRow(ctx, trabajadorPorAuthID, authUserID)
	var i Trabajador
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Nombre,
		&i.SucursalID,
		&i.EsVendedor,
		&i.Activo,
		&i.Desde,
		&i.Hasta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trabajadoresDelAlcance = `-- name: TrabajadoresDelAlcance :many
SELECT t.id, t.auth_user_id, t.nombre, t.sucursal_id, t.es_vendedor, t.activo, t.desde, t.hasta, t.created_at, t.updated_at
FROM trabajador t
WHERE t.activo AND t.es_vendedor
  AND ($1::text = '' OR t.sucursal_id = $1)
  AND (cardinality($2::text[]) = 0 OR t.id = ANY ($2))
  AND ($3::text = '' OR t.id <> $3)
ORDER BY t.nombre
`

type TrabajadoresDelAlcanceParams struct {
	SucursalID   string
	Trabajadores []string
	Excluir      string
}

func (q *Queries) TrabajadoresDelAlcance(ctx context.Context, arg TrabajadoresDelAlcanceParams) ([]Trabajador, error) {
	rows, err := q.db.Query(ctx, trabajadoresDelAlcance, arg.SucursalID, arg.Trabajadores, arg.Excluir)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trabajador{}
	for rows.Next() {
		var i Trabajador
		if err := rows.Scan(
			&i.ID,
			&i.AuthUserID,
			&i.Nombre,
			&i.SucursalID,
			&i.EsVendedor,
			&i.Activo,
			&i.Desde,
			&i.Hasta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ultimosBarridos = `-- name: UltimosBarridos :many
SELECT id, source_id, tipo, inicio, fin, ficheros_vistos, ficheros_nuevos, ficheros_error, puntos_insertados, ok, detalle FROM import_log ORDER BY inicio DESC LIMIT $1
`

func (q *Queries) UltimosBarridos(ctx context.Context, limit int32) ([]ImportLog, error) {
	rows, err := q.db.Query(ctx, ultimosBarridos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportLog{}
	for rows.Next() {
		var i ImportLog
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Tipo,
			&i.Inicio,
			&i.Fin,
			&i.FicherosVistos,
			&i.FicherosNuevos,
			&i.FicherosError,
			&i.PuntosInsertados,
			&i.Ok,
			&i.Detalle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vigenciasDeSupervisor = `-- name: VigenciasDeSupervisor :many
SELECT gestor_id, supervisor_id, desde, hasta
FROM supervision
WHERE supervisor_id = $1
`

type VigenciasDeSupervisorRow struct {
	GestorID     string
	SupervisorID string
	Desde        time.Time
	Hasta        *time.Time
}

func (q *Queries) VigenciasDeSupervisor(ctx context.Context, supervisorID string) ([]VigenciasDeSupervisorRow, error) {
	rows, err := q.db.Query(ctx, vigenciasDeSupervisor, supervisorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VigenciasDeSupervisorRow{}
	for rows.Next() {
		var i VigenciasDeSupervisorRow
		if err := rows.Scan(
			&i.GestorID,
			&i.SupervisorID,
			&i.Desde,
			&i.Hasta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
